'use strict';
const $=s=>document.querySelector(s);
const fixtures=[
 {hand:['3','3','5','5','8','8','A','A','2'],last:['7','7'],rec:['8','8'],title:'对 8',label:'跟牌',opponent:7,reason:'用较小的对子接住这一手，把对 A 留给后续局面。',facts:['对 8 可以合法压过地主的对 7。','你还持有对 A，可以应对更大的对子。'],alt:['A','A']},
 {hand:['3','3','5','5','A','A','2'],last:['9','9'],rec:['A','A'],title:'对 A',label:'跟牌',opponent:5,reason:'地主再次出了对子。你手中的对 A 可以接牌，单张 2 不能接对子。',facts:['对 A 大于当前桌面的对 9。','队友本轮不出，仍剩余 5 张。'],alt:[]},
 {hand:['3','3','5','5','2'],last:[],rec:['3','3'],title:'对 3',label:'主动出牌',opponent:5,reason:'两家都不出，现在由你领出。先处理手里的小对子。',facts:['当前是自由出牌，可以领出对 3。','这是预置教学选择，尚未经过真实策略评估。'],alt:['5','5']}
];
let step=0,selected=[],history=[],messages=[],uncertain=false,ended=false,version=1,view='library';
let preferences={verbosity:'简短',quiet:true};try{preferences={...preferences,...JSON.parse(localStorage.getItem('paiwise.preferences')||'{}')}}catch{}
const names={library:'游戏库',observer:'实时陪伴',live:'实时陪伴',review:'对局复盘',memory:'我的记忆',models:'模型配置'};
const suits=['♠','♥','♣','♦'];
function cardMarkup(rank,i,extra=''){return `<span class="card ${i%2?'red':''} ${extra}"><span>${rank}</span><span class="suit">${suits[i%4]}</span></span>`}
function cards(ranks){return ranks.map((r,i)=>cardMarkup(r,i)).join('')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3400)}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function showView(v){if(v==='live'&&currentGame!=='doudizhu')v='observer';if(!names[v])throw Error('Unknown view');view=v;window.scrollTo({top:0,behavior:'instant'});stopSpeech();document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==v);document.querySelectorAll('.nav').forEach(el=>{el.classList.toggle('active',el.dataset.view===(v==='observer'?'live':v));if(el.dataset.view===(v==='observer'?'live':v))el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});$('#breadcrumb').textContent=names[v];if(v==='library')renderLibrary();if(v==='observer')renderObserver();if(v==='review')renderReview();if(v==='memory')renderMemory();if(v==='models')renderModels();if(v==='live')render();}
function modal(title,html){$('#modal-title').textContent=title;$('#modal-content').innerHTML=html;$('#modal').showModal()}
function render(){const f=fixtures[step];$('#last-cards').innerHTML=cards(f.last);$('#last-label').textContent=f.last.length?'地主出牌':'两家不出 · 由你领出';$('#hand-count').textContent=f.hand.length;$('#opponent-count').textContent=f.opponent;$('#round-label').textContent=`第 ${step+1} / 3 个决策`;$('#hand').innerHTML=f.hand.map((r,i)=>`<button class="card ${f.hand.slice(0,i).filter(x=>x===r).length%2?'red':''} ${f.rec.includes(r)&&!uncertain&&!ended?'recommended':''} ${selected.includes(i)?'selected':''}" data-card="${i}" aria-label="${r} ${suits[f.hand.slice(0,i).filter(x=>x===r).length%2]}" aria-pressed="${selected.includes(i)}" ${ended?'disabled':''}><span>${r}</span><span class="suit">${suits[f.hand.slice(0,i).filter(x=>x===r).length%2]}</span></button>`).join('');$('#state-label').innerHTML=`${uncertain?'待确认局面':'已确认局面'} <b>v${version}</b>`;$('#turn-chip').textContent=ended?'演示片段已结束':uncertain?'暂停建议 · 等待纠正':'轮到你出牌';$('#selection-label').textContent=selected.length?`已选择 ${selected.length} 张`:'点击牌面，试试另一种选择';$('#recommendation-title').innerHTML=ended?'片段已完成':uncertain?'需要你确认':`${f.title} <span>${f.label}</span>`;$('#recommendation-cards').innerHTML=uncertain||ended?'':cards(f.rec);$('#recommendation-reason').textContent=ended?'三次决策已记录，去复盘看看你的选择。':uncertain?'当前牌面存在冲突。确认牌面后，才能给出可靠建议。':f.reason+(preferences.verbosity==='详细'?' '+f.facts.join(' '):'');$('#reason-facts').innerHTML=(uncertain||ended?[]:f.facts).map((t,i)=>`<div class="fact"><span>${i+1}</span>${t}</div>`).join('');$('#adopt').disabled=uncertain||ended;$('#pass').disabled=uncertain||ended||!f.last.length;$('#play-selected').disabled=uncertain||ended||!selected.length;$('#compare').disabled=uncertain||ended;$('#read-advice').disabled=uncertain||ended;$('#coach-subtitle').textContent=uncertain?'等待局面确认':ended?'查看本次选择记录':'当前局面已确认';$('#adopt').innerHTML='采用建议 <span>↗</span>';$('#timeline').innerHTML=history.length?history.slice(-3).map(h=>`<div class="event"><small>决策 ${h.step}</small>你出了 <b>${h.action}</b></div>`).join(''):`<div class="event"><small>上一个动作</small>地主 <b>对 7</b></div><div class="event"><small>接着</small>队友 <b>不出</b></div><div class="event"><small>现在</small>等待 <b>你的选择</b></div>`;renderChat();}
function rank(r){return ['3','4','5','6','7','8','9','10','J','Q','K','A','2'].indexOf(r)}
function play(action){if(currentGame!=='doudizhu')return toast('当前游戏没有出牌教学策略。');if(ended||uncertain)return toast('请先确认当前局面。');const f=fixtures[step];if(action.length===0&&!f.last.length)return toast('你是领出方，需要出牌。');if(action.length&&f.last.length&&(action.length!==2||action[0]!==action[1]||rank(action[0])<=rank(f.last[0])))return toast('当前需要比桌面更大的对子，或选择不出。');if(!f.last.length&&action.length&&!(action.length===1||(action.length===2&&action[0]===action[1])))return toast('这个教学片段支持单张或对子，请重新选择。');const same=JSON.stringify(action)===JSON.stringify(f.rec);stopSpeech();history.push({step:step+1,action:action.length? action.join(' · '):'不出',recommended:f.title,adopted:same,reason:f.reason});selected=[];messages=[];version++;if(!same||step===2){ended=true;render();toast(!same?'已记录你的选择。本分支结束，可在用户后台查看记录。':'演示完成，已记录三次决策。');showView('review');}else{step++;render();toast(preferences.quiet?'已进入你的下一次决策。':'对手回应已模拟：'+(fixtures[step].last.length?'地主出了对 '+fixtures[step].last[0]:'两家均不出')+'。')}}
function renderChat(){$('#chat-log').replaceChildren();for(const m of messages){const d=document.createElement('div');d.className='chat-bubble '+(m.role==='user'?'user':'');d.textContent=m.text;$('#chat-log').append(d)}$('#chat-log').scrollTop=$('#chat-log').scrollHeight}
function ask(q){q=q.trim();if(!q)return;if(uncertain)return toast('局面尚未确认，请先纠正牌面。');const f=fixtures[step];let answer;if(/队友|几张/.test(q))answer='当前教学局面里，队友还剩 5 张。对手具体手牌是未知信息。';else if(/为什么|对 A|对A/.test(q))answer=step===0?'对 A 也能压过对 7。这个示例先出对 8，是为了保留较大的对子；这是一条预置解释，不是已验证的最优策略。':f.reason;else if(/记住|简短|少说/.test(q)){preferences.verbosity='简短';preferences.quiet=true;savePrefs();answer='记住了：简短解释，只在你的回合提示。偏好保存在这个浏览器中。'}else answer='当前是交互演示，还不能调用模型回答开放问题。你可以试试“为什么这样出”“队友还剩几张”，或“记住，解释简短一点”。';messages.push({role:'user',text:q},{role:'assistant',text:answer});renderChat()}
function reset(){step=0;selected=[];history=[];messages=[];uncertain=false;ended=false;version++;stopSpeech();render();showView('live');toast('新演示已开始，个人偏好保留。')}
function renderReview(){if(currentGame!=='doudizhu')return renderObserverReview();$('#review').innerHTML=`<div class="page-heading"><div><div class="eyebrow">A MOMENT TO LOOK BACK</div><h1>回看这一局，带走一点经验。</h1><p>只复盘已发生的选择，不用一局输赢定义每一手。</p></div><button class="button secondary" data-reset>↻ 重新演示</button></div>${!history.length?`<div class="surface empty"><h2>还没有你的决策记录</h2><p>先在实时陪伴中试着出一手牌，回来看看。</p><button class="button primary" data-go="live">回到牌局</button></div>`:`<div class="notice">教学片段 · 共记录 ${history.length} 次选择 · 未模拟整局胜负</div><div class="content-grid"><div class="surface"><h2>关键决策</h2>${history.map(h=>`<div class="review-row"><span class="step-number">0${h.step}</span><div><h3>你的选择：${h.action}</h3><p>当时建议：${h.recommended}。${h.reason}</p><span class="pill ${h.adopted?'':'amber'}">${h.adopted?'采用了建议':'选择了其他动作'}</span><p style="margin-top:9px">${h.adopted?'采纳已记录，不等同于策略正确。':'这条分支尚未继续模拟，不能判断优于或劣于原建议。'}</p></div></div>`).join('')}</div><div><div class="surface"><h2>值得保留的经验</h2><p>面对对子时，比较“小对子先走”与“保留控制牌”的取舍。</p><span class="pill amber">候选经验 · 未验证</span><p style="margin-top:18px">这条示例暂不影响后续建议。需要更多局面和策略评测支持。</p><button class="text-button" data-go="memory">查看记忆状态 ↗</button></div><div class="surface"><h2>下一次，按你的节奏</h2><p>你可以随时调整提示频率和解释长度。</p><button class="text-button" data-go="memory">调整陪伴偏好 ↗</button></div></div></div>`}`;}
function savePrefs(){try{localStorage.setItem('paiwise.preferences',JSON.stringify(preferences))}catch{toast('浏览器不允许保存，偏好仅在本次页面有效。')}}
function renderMemory(){$('#memory').innerHTML=`<div class="page-heading"><div><div class="eyebrow">A LITTLE MORE FAMILIAR</div><h1>记住你，慢慢更默契。</h1><p>个人偏好跨游戏共享；游戏笔记与策略经验按游戏隔离。</p></div></div><div class="content-grid"><div><div class="surface"><h2>跨游戏陪伴偏好</h2><div class="setting-row"><div><strong>解释长度</strong><p>决定建议解释的呈现方式</p></div><select id="verbosity" aria-label="解释长度"><option ${preferences.verbosity==='简短'?'selected':''}>简短</option><option ${preferences.verbosity==='详细'?'selected':''}>详细</option></select></div><div class="setting-row"><div><strong>只在我的回合提示</strong><p>减少对局中的打扰</p></div><button class="switch" id="quiet-switch" role="switch" aria-label="只在我的回合提示" aria-checked="${preferences.quiet}"></button></div><p style="margin-top:16px">保存在当前浏览器，刷新后仍可保留。不会同步到其他设备。</p></div><div class="surface"><h2>策略经验</h2><div class="review-row"><span class="step-number">◇</span><div><h3>比较小对子与控制牌的取舍</h3><p>来源：教学示例。只用于说明经验如何被记录，不会改变出牌排序。</p><span class="pill amber">候选 · 待离线验证</span></div></div></div></div><div><div class="surface"><h2>记忆如何发挥作用</h2><ol class="explanation-list"><li>01 · 记下明确偏好<small>你说“解释简短点”，下次就按这个节奏。</small></li><li>02 · 保留决策和反馈<small>建议与实际动作分别记录。</small></li><li>03 · 验证策略经验<small>通过评测后，才可能影响策略。</small></li></ol></div><div class="surface"><h2>由你掌控</h2><p>清除后恢复默认偏好，不影响演示牌局。</p><button class="text-button" id="clear-memory">清除个人偏好</button></div></div></div>`;renderGameMemory();}
function renderModels(){$('#models').innerHTML=`<div class="page-heading"><div><div class="eyebrow">TWO MODELS, ONE COMPANION</div><h1>看清局面，想好下一手。</h1><p>按两路模型设计；当前站点运行预置交互，不发送画面或调用模型。</p></div><span class="pill amber">演示模式</span></div><div class="content-grid"><div class="surface model-card"><span class="model-number">01 / 视觉理解</span><h2>Qwen3-VL-4B</h2><code>Qwen/Qwen3-VL-4B-Instruct</code><p>规划职责：读取手牌、桌面出牌与轮次，输出带来源的结构化观察。</p><div class="model-status">待接入推理服务 · 无连接</div><a href="https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct" target="_blank" rel="noopener">查看模型资料 ↗</a></div><div class="surface model-card"><span class="model-number">02 / 推理与调度</span><h2>Qwen3.5-35B-A3B</h2><code>Qwen/Qwen3.5-35B-A3B</code><p>规划职责：调用游戏工具、比较候选动作、解释建议与生成候选复盘经验。</p><div class="model-status">待接入推理服务 · 无连接</div><a href="https://huggingface.co/Qwen/Qwen3.5-35B-A3B" target="_blank" rel="noopener">查看模型资料 ↗</a></div></div><div class="surface"><h2>端侧闭环 · 接入规划</h2><div class="model-flow"><span>画面</span>→<span>VL 识别</span>→<span>局面与规则校验</span>→<span>MoE ＋ 策略工具</span>→<span>文字建议</span></div><p style="margin-top:18px">正式版本由本地应用提供屏幕采集、本机模型推理、游戏工具和本地存储。需要先下载模型与游戏包并完成硬件测试；当前页面尚不具备这些能力。本 UX 原型不收集密钥。语音朗读使用浏览器能力，独立于这两路模型。</p></div>`;}
function compare(){const f=fixtures[step];modal('看看其他选择',`<p>以下是预置教学对比，没有真实胜率或推理分数。</p><div class="compare-row recommended"><strong>${f.title}<span class="pill">示例推荐</span></strong><p>${f.reason}</p></div>${f.alt.length?`<div class="compare-row"><strong>对 ${f.alt[0]}</strong><p>也可以合法出牌，但会消耗不同点数的对子。实际优劣需要策略工具评估。</p></div>`:''}${f.last.length?'<div class="compare-row"><strong>不出</strong><p>保留手牌，将行动交给下家。后续收益取决于隐藏手牌和双方策略。</p></div>':''}`)}
function correction(){if(ended)return toast('片段已结束，请重新演示后纠正。');uncertain=true;version++;stopSpeech();render();const current=fixtures[step].last[0];modal('确认桌面上的牌',`<p>进入纠错后，旧建议已暂停。此教学场景的确认结果为${current?'“对 '+current+'”':'“空桌面，由你领出”'}。</p><label for="correction-value">确认结果</label><select id="correction-value"><option value="correct">${current?'对 '+current:'空桌面，由我领出'}</option><option value="unknown">仍然看不清</option></select><div class="modal-actions"><button class="button secondary" id="keep-paused">保持暂停</button><button class="button primary" id="confirm-correction">确认局面</button></div>`)}
function details(){modal('这一手的陪伴过程',`<p>这是流程演示，各步骤未调用真实模型。</p><ol class="explanation-list"><li>01 · 观察<small>读取预置手牌和公开出牌。</small></li><li>02 · 校验<small>确认当前局面 v${version}，检查出牌类型。</small></li><li>03 · 建议<small>展示预置候选；MoE 接入后负责工具调度与解释。</small></li><li>04 · 反馈<small>分别记录推荐动作和你的实际选择。</small></li></ol>`)}
document.addEventListener('click',e=>{if(e.target.closest('.brand')){e.preventDefault();showView('library');return}const t=e.target.closest('button');if(!t)return;if(t.dataset.view)return showView(t.dataset.view);if(t.dataset.go)return showView(t.dataset.go);if(t.hasAttribute('data-reset'))return reset();if(t.dataset.card!==undefined){const i=Number(t.dataset.card);selected=selected.includes(i)?selected.filter(n=>n!==i):[...selected,i].sort((a,b)=>a-b);return render()}if(t.dataset.question)return ask(t.dataset.question);switch(t.id){case'reset':reset();break;case'settings-shortcut':showView('models');break;case'adopt':play([...fixtures[step].rec]);break;case'pass':play([]);break;case'play-selected':play(selected.map(i=>fixtures[step].hand[i]));break;case'compare':compare();break;case'correction-trigger':correction();break;case'close-modal':case'keep-paused':$('#modal').close();break;case'confirm-correction':if($('#correction-value').value==='unknown'){toast('建议保持暂停。可再次点击“识别有误？”确认。');$('#modal').close()}else{uncertain=false;version++;render();$('#modal').close();toast('局面已确认，建议恢复。')}break;case'loop-details':details();break;case'quiet-switch':preferences.quiet=!preferences.quiet;savePrefs();renderMemory();toast('已保存提示偏好。');break;case'clear-memory':modal('清除个人偏好？','<p>恢复简短解释与仅在你的回合提示。当前演示记录会保留。</p><div class="modal-actions"><button class="button secondary" id="close-modal">取消</button><button class="button primary" id="confirm-clear">清除偏好</button></div>');break;case'confirm-clear':preferences={verbosity:'简短',quiet:true};try{localStorage.removeItem('paiwise.preferences')}catch{}$('#modal').close();renderMemory();toast('已恢复默认偏好。');break;case'read-advice':if(!('speechSynthesis'in window))return toast('当前浏览器不支持朗读。');stopSpeech();const utterance=new SpeechSynthesisUtterance(`建议出${fixtures[step].title}。${fixtures[step].reason}`);utterance.lang='zh-CN';speechSynthesis.speak(utterance);toast('使用浏览器语音朗读，可切换页面停止。');break;}});
$('#ask-form').addEventListener('submit',e=>{e.preventDefault();ask($('#question').value);$('#question').value=''});
document.addEventListener('change',e=>{if(e.target.id==='verbosity'){preferences.verbosity=e.target.value;savePrefs();toast('已保存解释长度。')}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close()});
render();showView('library');
// The page exposes the same bounded prototype actions to supported browser agents.
const toolLifecycle=new AbortController();
if(document.modelContext?.registerTool){
 const definitions=[
  {name:'read_demo_state',title:'读取教学局面',description:'Read this prototype state; no model inference or real game access.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {view,game:currentGame,scope:gameScope(),step:currentGame==='doudizhu'?step+1:null,stateVersion:version,paused:uncertain,ended:currentGame==='doudizhu'?ended:false,hand:currentGame==='doudizhu'?fixtures[step].hand:[],recommended:currentGame==='doudizhu'?fixtures[step].rec:[],decisions:currentGame==='doudizhu'?history.length:0,mode:currentGame==='doudizhu'?'scripted_demo':'manual_observation'}}},
  {name:'navigate_demo_view',title:'切换原型页面',description:'Navigate between the game simulator and user workspace. Legacy review and memory routes open the user workspace.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['library','live','backend','review','memory','models']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length!==1||!names[input.view])throw Error('Invalid view');showView(input.view);return {view}}},
  {name:'adopt_demo_advice',title:'采用演示建议',description:'Simulate adopting the current recommendation. Changes only the in-page teaching game and records a demo decision.',inputSchema:{type:'object',properties:{stateVersion:{type:'integer'}},required:['stateVersion'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length!==1||input.stateVersion!==version||ended||uncertain||currentGame!=='doudizhu')throw Error('Stale or unavailable demo advice');play([...fixtures[step].rec]);return {stateVersion:version,ended,decisions:history.length}}}
 ];
 for(const tool of definitions){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:toolLifecycle.signal})).catch(()=>{})}catch{}}
 window.addEventListener('pagehide',()=>toolLifecycle.abort(),{once:true});
}
