'use strict';
const gamePacks=[
 {id:'sanguosha',name:'三国杀',symbol:'杀',category:'基础牌攻防',mode:'教学模拟',desc:'杀、闪、桃与回合响应。',color:'crimson',adapter:true,rule:'简化基础牌 · 四回合练习'},
 {id:'doudizhu',name:'斗地主',symbol:'♠',category:'三人牌局',mode:'教学演示可用',desc:'出牌建议、局面纠错、追问与复盘。',color:'forest',adapter:true,rule:'标准三人 · 出牌阶段'},
 {id:'guandan',name:'掼蛋',symbol:'双',category:'四人协作',mode:'简化教学模拟',desc:'先体验观察与记录，后续接入配合策略。',color:'blue',adapter:true,rule:'规则版本待选择'},
 {id:'mahjong',name:'麻将',symbol:'東',category:'牌效与判断',mode:'简化教学模拟',desc:'先记录可见局面，具体玩法需独立适配。',color:'ochre',adapter:true,rule:'麻将规则待选择'},
 {id:'spire',name:'杀戮尖塔',symbol:'Ⅰ',category:'单人卡牌',mode:'简化教学模拟',desc:'为战斗、选卡和路线保留观察记录。',color:'plum',adapter:true,rule:'游戏版本待确认'},
 {id:'chess',name:'国际象棋',symbol:'♞',category:'棋盘策略',mode:'简化教学模拟',desc:'统一陪伴界面，棋盘与引擎接入待完成。',color:'slate',adapter:true,rule:'标准规则 · 待接入'},
 {id:'custom',name:'其他游戏',symbol:'＋',category:'自定义会话',mode:'通用回合沙盘',desc:'输入游戏名称，建立独立的会话与笔记。',color:'neutral',adapter:true,rule:'自定义 · 未适配'}
];
let currentGame='doudizhu',pendingGame='doudizhu',customName='',observerStage='idle';
let gameNotes={};try{const n=JSON.parse(localStorage.getItem('paiwise.gameNotes')||'{}');if(n&&typeof n==='object'&&!Array.isArray(n))gameNotes=n}catch{}
const observations={};
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function currentPack(){return gamePacks.find(g=>g.id===currentGame)}
function gameTitle(){return currentGame==='custom'?(customName||'其他游戏'):currentPack().name}
function gameScope(){return currentGame==='custom'?'custom:'+customName:currentGame}
function saveGameNotes(){try{localStorage.setItem('paiwise.gameNotes',JSON.stringify(gameNotes))}catch{toast('无法持久保存，笔记仅在当前页面有效。')}}
function renderLibrary(){const available=gamePacks.filter(g=>g.adapter).length;$('#library').innerHTML=`<div class="page-heading"><div><div class="eyebrow">YOUR GAMES. YOUR COMPANION.</div><h1>今天，一起玩什么？</h1><p>选择游戏，共用一位搭子。每款游戏有自己的局面、工具和经验。</p></div><button class="button secondary" data-go="models">本地运行设置 ↗</button></div><div class="library-status"><div><span class="status-icon">⌂</span><strong>端侧优先</strong><span>目标：观察、决策、记忆均在本机完成</span></div><span class="pill amber">当前仅 UX 演示 · 模型未连接</span></div><div class="section-title"><h2>游戏库 <span class="muted">/ ${gamePacks.length-1} 款游戏 + 自定义</span></h2><span>${available} 个专项教学演示</span></div><div class="game-grid">${gamePacks.map(g=>`<article class="game-tile"><div class="game-tile-top ${g.color}"><span class="game-symbol" aria-hidden="true">${g.symbol}</span><span class="game-type">${g.category}</span></div><div class="game-tile-body"><div class="game-title"><h2>${g.name}</h2>${g.id===currentGame?'<span class="pill">当前选择</span>':''}</div><p>${g.desc}</p><div class="game-availability ${g.adapter?'ready':''}">${g.mode}</div><button class="button ${g.adapter?'primary':'secondary'}" data-select-game="${g.id}">${g.adapter?'进入教学演示':'体验通用观察'} <span>↗</span></button></div></article>`).join('')}</div><div class="library-explainer"><div><strong>同一套陪伴框架</strong><p>模型调度、提示、复盘和用户偏好共用。</p></div><div><strong>每款游戏独立适配</strong><p>规则、识别与策略逐款接入，不混用经验。</p></div><div><strong>未知时，明确告诉你</strong><p>没有专项适配的游戏，不输出伪装成可靠策略的建议。</p></div></div>`;}
function prepareGame(id){const g=gamePacks.find(x=>x.id===id);if(!g)throw Error('Unknown game');pendingGame=id;modal('开始前，确认一下',`<div class="prepare-game"><span class="prepare-icon ${g.color}">${g.symbol}</span><div><h3>${g.name}</h3><p>${g.rule}</p></div></div>${id==='custom'?'<label for="custom-game-name">游戏名称</label><input id="custom-game-name" maxlength="40" placeholder="例如：星露谷物语" value="'+escapeHTML(customName)+'">':''}<div class="check-list"><div><span>界面与演示资源</span><b class="check-ok">已就绪</b></div><div><span>Qwen3-VL-4B · 本地视觉</span><b>尚未连接</b></div><div><span>Qwen3.5-35B-A3B · 本地推理</span><b>尚未连接</b></div><div><span>游戏专项能力</span><b>${g.adapter?'预置教学片段':'待适配'}</b></div><div><span>偏好与游戏笔记</span><b class="check-ok">当前浏览器保存</b></div></div><div class="notice">${g.adapter?'演示使用预置牌局与建议，不调用模型。':'通用观察只展示记录与反馈流程，不包含游戏识别或策略推理。'}真实端侧模式还需本地应用、模型资源与设备测试。</div><div class="modal-actions"><button class="button secondary" disabled>真实端侧模式 · 未就绪</button><button class="button primary" id="start-game-demo">${g.adapter?'进入教学演示':'进入观察流程'}</button></div>`);}
function startGame(){if(pendingGame==='custom'){const n=$('#custom-game-name').value.trim();if(!n)return toast('先输入游戏名称。');customName=n}currentGame=pendingGame;version++;selected=[];messages=[];uncertain=false;observerStage='idle';stopSpeech();$('#modal').close();showView('live');toast('已切换到'+gameTitle()+'，旧建议已失效。');}
function renderObserver(){const title=escapeHTML(gameTitle());const records=observations[gameScope()]||[];$('#observer').innerHTML=`<div class="page-heading"><div><div class="eyebrow">ONE COMPANION, ANY GAME</div><h1>${title} <span class="heading-mode">通用观察</span></h1><p>先记录你看到的局面，再交给未来接入的本地能力。</p></div><button class="button secondary" data-go="library">切换游戏</button></div><div class="notice">专项游戏包未适配 · 当前不采集屏幕、不调用模型、不提供胜率或最佳动作。</div><div class="content-grid"><div><div class="surface observation-surface"><div class="section-title"><h2>当前观察</h2><span>手动输入 · UX 演示</span></div><label for="observation-text">描述你现在看到的局面</label><textarea id="observation-text" rows="5" maxlength="500" placeholder="例如：轮到我行动，想比较进攻与防守的选择。"></textarea><div class="observation-actions"><button class="button secondary" id="fill-observation">填入流程示例</button><button class="button primary" id="record-observation">记录这次观察</button></div><p>只保存你主动输入的文字，不会读取其他窗口。</p></div><div class="surface"><h2>本次记录 <span class="muted">${records.length}</span></h2>${records.length?records.map((r,i)=>`<div class="review-row"><span class="step-number">${i+1}</span><div><p>${escapeHTML(r.text)}</p><span class="pill">用户观察</span><span class="pill amber">未经过模型验证</span></div></div>`).join(''):'<p>记录会出现在这里，切换游戏后按游戏分别保留；刷新页面会清空本次记录。</p>'}</div></div><div><div class="surface"><div class="section-title"><h2>牌伴工作状态</h2><span class="pill amber">${records.length?'等待本地能力':'等待观察'}</span></div><ol class="explanation-list"><li>① 观察<small>${records.length?'已收到你的描述。':'等待你描述当前局面。'}</small></li><li>② 理解与判断<small>本地 VL、MoE 和游戏工具尚未接通。</small></li><li>③ 建议<small>暂不生成动作建议。</small></li><li>④ 反馈与记忆<small>可将自己的总结保存为游戏笔记。</small></li></ol><button class="button secondary" data-go="memory">写一条游戏笔记 ↗</button></div><div class="surface"><h2>让它真正懂这款游戏</h2><p>需要接入画面识别、局面字段、规则与策略工具。陪伴界面和记忆系统继续复用。</p><button class="text-button" data-go="models">查看本地能力规划 ↗</button></div></div></div>`;}
function renderGameMemory(){const section=document.createElement('div');section.className='surface scoped-memory';const notes=Array.isArray(gameNotes[gameScope()])?gameNotes[gameScope()]:[];section.innerHTML=`<div class="section-title"><h2>${escapeHTML(gameTitle())} · 独立游戏笔记</h2><span>不会用于其他游戏</span></div><p>你自己的观察和复盘，不会自动变成已验证策略。</p><div class="note-compose"><input id="game-note" aria-label="当前游戏笔记" maxlength="240" placeholder="记一条只属于这款游戏的经验…"><button class="button primary" id="save-game-note">保存笔记</button></div>${notes.map(n=>`<div class="review-row"><span class="step-number">◇</span><div><p>${escapeHTML(n.text)}</p><span class="pill">用户笔记</span><span class="pill amber">未验证</span></div></div>`).join('')}`;$('#memory').append(section);if(currentGame!=='doudizhu'){const blocks=$('#memory').querySelectorAll('.surface');for(const block of blocks){if(block.querySelector('h2')?.textContent==='策略经验')block.innerHTML='<h2>策略经验</h2><p>当前游戏尚无已验证策略经验。斗地主教学经验不会在这里使用。</p>'}}}
function renderObserverReview(){$('#review').innerHTML=`<div class="page-heading"><div><div class="eyebrow">REVIEW YOUR OBSERVATIONS</div><h1>${escapeHTML(gameTitle())} · 观察回顾</h1><p>这里仅展示你记录的内容，没有自动生成的策略结论。</p></div><button class="button secondary" data-go="live">返回观察</button></div><div class="surface">${(observations[gameScope()]||[]).length?(observations[gameScope()]||[]).map((r,i)=>`<div class="review-row"><span class="step-number">${i+1}</span><p>${escapeHTML(r.text)}</p></div>`).join(''):'<div class="empty"><h2>还没有观察记录</h2><p>在陪伴工作台记录局面后，可以回到这里查看。</p></div>'}</div><button class="button primary" data-go="memory">记录我的总结</button>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.selectGame)return prepareGame(b.dataset.selectGame);if(b.id==='start-game-demo')return startGame();if(b.id==='fill-observation'){$('#observation-text').value='轮到我行动。我想比较不同选择，并在结束后记录自己的判断。';return}if(b.id==='record-observation'){const text=$('#observation-text').value.trim();if(!text)return toast('先输入当前局面。');const key=gameScope();(observations[key]??=[]).push({text});version++;renderObserver();return toast('已记录，可在用户后台结合局面提问。')}if(b.id==='save-game-note'){const text=$('#game-note').value.trim();if(!text)return toast('先写下你的笔记。');const key=gameScope();if(!Array.isArray(gameNotes[key]))gameNotes[key]=[];gameNotes[key].push({text,createdAt:Date.now()});saveGameNotes();renderMemory();toast('已保存到'+gameTitle()+'的独立笔记。')}});
