/* Local UI translations. User-authored notes, questions and replies are preserved. */
(function(){
'use strict';
const dictionary={
'牌伴':'Paiwise','两个界面，一位搭子':'Two workspaces, one companion','游戏模拟':'Game simulator','用户后台':'User workspace','熟悉你的节奏':'Learning your play style','每一局的陪伴，':'A companion for every game,','从记住你的偏好开始。':'starting with your preferences.','我的工作台':'My workspace','工作台':'Workspace','你':'You','UX 原型 · 多游戏':'UX prototype · Multiple games','实时陪伴':'Live companion','牌局模拟 · 预置片段':'Simulation · Preset scenarios','打开模型配置':'Open assistant settings','公开演示版：支持游戏模拟、偏好与出牌记录。智能问答尚未连接云端服务。':'Public demo: play simulations, save preferences and review decisions. AI chat is not connected to a cloud service.','一起想好每一手。':'Think through every move together.','演示内容 · 不连接真实牌局':'Demo content · No connection to live games',
'先选一款游戏。':'Choose a game to play.','前台体验对局，后台了解你的选择。':'Play a match, then explore your choices in your workspace.','查看用户后台 ↗':'Open user workspace ↗','每款游戏，都有模拟对局':'A playable simulation for every game','手动操作或自动播放，每个游戏独立记录。':'Play manually or use auto-play. Each game keeps its own history.','同一套用户记忆':'One shared memory framework','当前游戏':'Current game','进入模拟对局 ↗':'Play simulation ↗','进入模拟对局':'Play simulation','三国杀':'Sanguosha','斗地主':'Dou Dizhu','掼蛋':'Guandan','麻将':'Mahjong','杀戮尖塔':'Slay the Spire','国际象棋':'Chess','其他游戏':'Other games','基础牌攻防':'Five-player identity game','五人身份对局':'Five-player identity game','三人牌局':'Three-player cards','四人协作':'Four-player partnership','牌效与判断':'Tile efficiency','单人卡牌':'Solo deck-building','棋盘策略':'Board strategy','自定义会话':'Custom session','双':'2×','東':'E','杀':'Slash','五人身份对局：武将技能、装备锦囊、濒死救援与身份胜负。':'Five-player identities, general skills, equipment, tactics, rescue and faction victory.','三次出牌决策，比较保留与抢出。':'Three decisions: compare holding back with taking the lead.','普通对子跟牌，比较接牌与让牌。':'Practice pair responses and compare playing with passing.','三次摸打练习，观察手牌与弃牌变化。':'Three draw-and-discard decisions to explore your hand.','能量、格挡与敌人意图的战斗练习。':'Practice combat with energy, block and enemy intentions.','选择合法开局分支，黑方自动回应。':'Choose a legal opening move; Black responds automatically.','通用回合沙盘，自定义游戏名称。':'A turn-based sandbox with a custom game name.',
'切换游戏':'Switch game','重新开始':'Restart','播放模拟':'Auto-play','暂停模拟':'Pause auto-play','模拟对局':'Simulation','简化教学 · 本机运行':'Teaching demo · Runs locally','每次操作更新局面，记录同步到用户后台。':'Every move updates the position and your workspace history.','进行中':'In progress','已结束':'Finished','南家':'South','北家':'North','东 / 西家':'East / West','脚本控制':'Scripted','自动摸打':'Automatic draws and discards','东家':'East','其他三家':'Other three players','已弃牌':'Discards','你的生命':'Your health','训练敌人':'Training enemy','能量 / 格挡':'Energy / Block','白方':'White','黑方 · 固定回应':'Black · Scripted responses','对手':'Opponent','队友':'Partner','阶段':'Phase','生命':'Health','资源':'Resources','推进':'Progress','累计推进点数':'Progress points','请选择一张手牌打出':'Select a tile to discard','白方行棋 · 从下方选择开局走法':'White to move · Choose an opening below','选择本回合的策略':'Choose your strategy for this turn','你获得领出权，可以出任意手中对子':'You lead: play any pair from your hand','请选择更大的对子':'Choose a higher pair','选择你的动作':'Choose your move','只列出当前可用动作':'Only legal actions are shown','本次练习结束':'Practice finished','再来一局':'Play again','查看本游戏记录 ↗':'View this game’s history ↗','对局动态':'Match events','最近 6 次':'Latest 6 moves','等待你的第一步操作。':'Waiting for your first move.','教学提示':'Practice tips','本次练习完成，可以到后台回看不同选择。':'Practice complete. Review your choices in your workspace.','等待下一回合':'Waiting for the next turn','提示由固定规则生成，不是模型推理，也不代表最优策略。':'Tips come from fixed rules, not model inference, and are not guaranteed to be optimal.','用户后台 ↗':'User workspace ↗','本练习的规则范围':'Practice rules and scope','偏好与记忆':'Preferences and memory','手动操作和自动播放分别记录；本游戏的记录不会混入其他游戏。':'Manual and automated decisions are tracked separately for each game.','当前棋盘':'Current board','当前手牌':'Current hand','空':'Empty','能量':'Energy','格挡':'Block','伤害':'Damage','打击':'Strike','防御':'Defend','重击':'Heavy Strike','进攻':'Attack','防守':'Defend','休整':'Rest','结束回合':'End turn','不出':'Pass','桌面':'Table','示例选择':'Suggested example','回复':'Restore',
'跟牌练习：本片段只使用普通对子，按 3 至 A 比大小。固定打 2，手中无级牌或逢人配；不含炸弹、进贡和升级结算。':'Pair-response practice: ordinary pairs rank from 3 to A. Level 2 is fixed; no level cards or wild cards are in this hand. Bombs, tribute and promotion are not included.',
'摸打一张练习：固定 14 张手牌，每次打出一张后进入下一次摸牌。共 3 次选择；不含吃碰杠、胡牌与番数计算。':'Draw-and-discard practice with 14 tiles and three decisions. Each discard is followed by the next draw. Chow, pung, kong, winning hands and scoring are not included.',
'简化战斗：每回合 3 点能量，打击造成 6 伤害、防御获得 5 格挡、重击造成 9 伤害并消耗 2 能量。固定抽牌与敌人意图，不含遗物、易伤与地图。':'Simplified combat: 3 energy per turn. Strike deals 6 damage, Defend grants 5 block, and Heavy Strike costs 2 energy for 9 damage. Draws and enemy intentions are fixed; relics, Vulnerable and map choices are not included.',
'开局分支练习：选择预设合法走法，黑方自动回应。每条线路 3 个白方回合，不是完整棋力引擎，也不判断整局胜负。':'Opening practice with preset legal moves and automatic Black replies. Each branch has three White turns. This is not a complete chess engine and does not determine a match winner.',
'通用回合沙盘：进攻消耗 2 资源并推进 2 点，防守消耗 1 资源抵挡反击，休整恢复 2 资源。共 4 回合；这是自定义模板，不代表所填游戏的真实规则。':'A four-turn sandbox: Attack costs 2 resources and gains 2 progress; Defend costs 1 resource and blocks retaliation; Rest restores 2 resources. This template does not implement the actual rules of your named game.',
'你的选择，助手都跟得上。':'A workspace for your decisions.','记录留在当前浏览器；提问时发送本游戏相关上下文。':'History stays in this browser. Questions send context for the selected game.','返回游戏 ↗':'Back to game ↗','亲自出牌':'Manual decisions','采用教学建议':'Suggestions followed','自动模拟':'Auto-play','模拟记录与真实手动操作分开统计。':'Manual and automated decisions are counted separately.','少量选择不用于判断稳定的出牌风格。':'A few decisions cannot establish a consistent play style.','我的出牌偏好':'My play preferences','本人确认':'Confirmed by you','希望助手记住什么':'What should the assistant remember?','例如：先给结论；出大牌前提醒我比较保留控制权的价值。':'For example: lead with the recommendation; remind me to consider keeping control before playing high cards.','保存偏好':'Save preferences','只用于这款游戏。可以随时编辑或清空，不会自动变成已验证策略。':'Applies only to this game. Edit or clear it anytime; preferences do not become validated strategies.','回答长度':'Answer length','简短':'Brief','详细':'Detailed','从出牌里观察':'Insights from your decisions','还没有手动出牌记录。先去前台试一手，记录会自动出现在这里。':'No manual decisions yet. Play a move and it will appear here.','当前仅展示行为证据，尚不足以判定“激进”或“保守”。':'These records alone cannot determine whether your style is aggressive or cautious.','请助手分析这些选择 ↗':'Ask the assistant to review these choices ↗','助手设置':'Assistant settings','推理':'Reasoning','截图识别模型':'Screenshot model','选择视觉模型':'Choose a vision model','硅基流动未提供指定的 VL 4B 版本，请选择替代模型。当前为云端推理，端侧模式尚未实现。':'The requested VL 4B model is unavailable from SiliconFlow. Choose an alternative. Inference is cloud-based; on-device inference is not yet implemented.','问问你的游戏助手':'Ask your game assistant','结合当前局面、出牌记录与已保存偏好回答':'Answers use the position, decisions and saved preferences','教学局面':'Practice position','这一手怎么出？':'What should I play?','你了解我的习惯吗？':'What do you know about my play style?','你的问题':'Your question','比如：我刚刚保留对 A，这个选择有哪些取舍？':'For example: I kept my pair of Aces. What are the trade-offs?','＋ 添加游戏截图':'+ Add a screenshot','发送问题 ↑':'Send question ↑','正在回答…':'Answering…','移除截图':'Remove screenshot','待发送游戏截图':'Screenshot to send','发送时才调用云端模型。建议未经游戏规则引擎验证，不自动替你出牌。':'Cloud models are called only when you send a question. Advice is not rule-validated and will not play cards for you.','出牌记录':'Decision history','刷新后保留':'Saved across reloads','时间 / 来源':'Time / Source','局面':'Position','实际选择':'Your choice','教学建议':'Suggested choice','是否一致':'Match','手动出牌':'Manual play','自由领出':'Free lead','一致':'Matched','不同选择':'Different choice','还没有这一款游戏的出牌记录':'No decisions recorded for this game yet','在前台出牌或播放模拟后，这里会同步更新。':'Play manually or start auto-play to populate this history.','连接中':'Connecting','已连接':'Connected','未连接':'Not connected','公开演示 · 问答未接入':'Public demo · AI chat offline','助手 · 等待连接':'Assistant · Waiting for connection','从你刚刚的那一手开始。':'Start with your last move.','可以问出牌理由、比较其他选择，或回看自己的习惯。':'Ask about a move, compare alternatives or review your habits.','未能完成':'Unable to complete','云端回答':'Cloud response','正在调用模型，请稍候…':'Calling the model, please wait…',
'选择其他游戏':'Choose another game','游戏名称':'Game name','输入游戏名称':'Enter a game name','使用通用回合沙盘，建立独立的模拟记录与偏好。':'Use the turn-based sandbox with a separate history and preferences.','关闭':'Close','在牌桌上，试试你的选择。':'Try your choices at the table.','亲自出牌，或播放模拟。每次选择都会同步到用户后台。':'Play yourself or start auto-play. Every choice is saved in your workspace.','经典斗地主':'Classic Dou Dizhu','教学演示':'Practice demo','识别有误？':'Incorrect position?','牌 伴':'PAIWISE','陆先生':'Mr. Lu','小林':'Lin','陆':'Lu','林':'Lin','地主':'Landlord','地主出牌':'Landlord played','轮到你出牌':'Your turn','我的手牌':'My hand','点击牌面，试试另一种选择':'Select cards to explore another move','浅绿色边框是当前建议出牌':'Light-green outlines indicate the suggested cards','出选中的牌':'Play selected cards','牌局动态':'Match events','公开信息':'Public information','牌伴的建议':'Paiwise’s suggestion','当前局面已确认':'Position confirmed','使用浏览器朗读建议':'Read suggestion aloud','这一手，建议你出':'Suggested move','跟牌':'Respond','主动出牌':'Lead','采用建议':'Use suggestion','预置策略示例 · 不代表模型实际判断':'Preset strategy example · Not a model recommendation','为什么这样出？':'Why this move?','比较其他选择 ↗':'Compare alternatives ↗','这一手，为什么这样选？':'Why choose this move?','在用户后台查看出牌记录、更新偏好，继续向助手提问。':'Review decisions, update preferences and ask questions in your workspace.','打开用户后台 ↗':'Open user workspace ↗','陪伴循环':'Companion loop','① 看见局面':'① Observe','② 判断出牌':'② Evaluate','③ 给出建议':'③ Suggest','④ 记住反馈':'④ Remember','查看过程 ↗':'View the process ↗','用较小的对子接住这一手，把对 A 留给后续局面。':'Respond with the smaller pair, keeping the Aces for later.','对 8 可以合法压过地主的对 7。':'Your pair of 8s legally beats the Landlord’s pair of 7s.','你还持有对 A，可以应对更大的对子。':'Your pair of Aces can respond to higher pairs.','地主再次出了对子。你手中的对 A 可以接牌，单张 2 不能接对子。':'The Landlord played another pair. Your Aces can respond; a single 2 cannot beat a pair.','对 A 大于当前桌面的对 9。':'A pair of Aces beats the pair of 9s on the table.','队友本轮不出，仍剩余 5 张。':'Your partner passes and still has 5 cards.','两家都不出，现在由你领出。先处理手里的小对子。':'Both opponents passed. You lead; clear a small pair first.','当前是自由出牌，可以领出对 3。':'You have a free lead and may play a pair of 3s.','这是预置教学选择，尚未经过真实策略评估。':'This is a preset teaching choice, not a validated strategy.',
'王兵开局':'King’s Pawn opening','后兵开局':'Queen’s Pawn opening','出马':'Develop knight','出象':'Develop bishop','一万':'1 Characters','二万':'2 Characters','三万':'3 Characters','四万':'4 Characters','五万':'5 Characters','六万':'6 Characters','七万':'7 Characters','八万':'8 Characters','九万':'9 Characters','一筒':'1 Dots','二筒':'2 Dots','三筒':'3 Dots','四筒':'4 Dots','五筒':'5 Dots','六筒':'6 Dots','七筒':'7 Dots','八筒':'8 Dots','九筒':'9 Dots','七条':'7 Bamboo','八条':'8 Bamboo','九条':'9 Bamboo','东':'East','白':'White Dragon','双':'2×',
'保留手牌，让过这一手':'Keep your cards and pass','压过当前对子':'Beat the current pair','主动领出对子':'Lead with a pair','选择一张弃牌':'Choose a tile to discard','消耗 1 能量，造成 6 伤害':'Cost: 1 energy · Deal 6 damage','消耗 1 能量，获得 5 格挡':'Cost: 1 energy · Gain 5 block','消耗 2 能量，造成 9 伤害':'Cost: 2 energy · Deal 9 damage','结束行动，结算敌人攻击':'End actions and resolve the enemy attack','消耗 2 资源，推进 2 点':'Cost: 2 resources · Gain 2 progress','消耗 1 资源，抵挡反击':'Cost: 1 resource · Block retaliation','恢复 2 资源，但会受到反击':'Restore 2 resources; take retaliation damage'
};
Object.assign(dictionary,{
'已确认局面':'Confirmed position','牌伴首页':'Paiwise home','主导航':'Main navigation','选择游戏':'Choose game','行动回合':'Turn','对手使用杀':'Opponent plays Slash','对对手使用杀':'Slash the opponent','打出闪':'Play Dodge','结束出牌':'End play phase','使用桃':'Use Peach','成功抵挡':'Attack blocked',
'打出这两张牌':'Play these two cards','保留手牌，进入下一次预置局面':'Keep your cards and move to the next preset position','打出一张，观察下一次摸牌':'Discard one tile and see the next draw','敌人攻击，之后补满能量并抽取固定手牌':'The enemy attacks; then energy and preset cards are replenished','消耗 2 资源，推进 2 点；受到 1 点反击':'Spend 2 resources, gain 2 progress and take 1 retaliation damage','消耗 1 资源，抵挡本回合反击':'Spend 1 resource to block this turn’s retaliation','恢复 2 资源；受到 1 点反击':'Restore 2 resources and take 1 retaliation damage','其余座位动作按教学脚本推进':'Other players follow the teaching script','下次桌面为对 9':'Next position: pair of 9s','下次局面由你领出':'You lead in the next position','跟牌片段完成，未模拟整局名次':'Response practice complete; full-match rankings are not simulated','三次摸打完成，未计算胡牌与番数':'Three draws and discards complete; winning hands and scoring are not evaluated','其他三家依次出牌，轮到你摸到':'The other players have moved. You draw ','击败训练敌人，战斗结束':'Training enemy defeated. Combat finished.','生命耗尽，战斗结束':'Health depleted. Combat finished.','四回合训练结束，敌人尚未被击败':'Four turns complete. The enemy remains undefeated.','开局片段完成，未判断整局胜负':'Opening practice complete. No full-match winner is determined.','黑方回应':'Black responds','四回合沙盘结束，累计推进':'Four-turn sandbox finished. Total progress: ','生命耗尽，沙盘结束':'Health depleted. Sandbox finished.','获得 5 格挡':'Gain 5 block','造成 6 点伤害':'Deal 6 damage','造成 9 点伤害':'Deal 9 damage','使用打击':'Use Strike','使用防御':'Use Defend','使用重击':'Use Heavy Strike','打出':'Play ','消耗':'Cost:','敌人攻击，你受到':'Enemy attacks; you take ','点伤害':'damage','点反击':'retaliation damage',
'上一个动作':'Previous action','接着':'Next','现在':'Now','等待':'Waiting','你的选择':'Your choice','你出了':'You played','两家不出 · 由你领出':'Both passed · You lead','演示片段已结束':'Scenario finished','片段已完成':'Scenario complete','查看本次选择记录':'Review your choices','三次决策已记录，去复盘看看你的选择。':'Three decisions recorded. Review your choices in the workspace.','已进入你的下一次决策。':'Your next decision is ready.','演示完成，已记录三次决策。':'Demo complete. Three decisions saved.','新演示已开始，个人偏好保留。':'New demo started. Your preferences are preserved.','已记录你的选择。本分支结束，可在用户后台查看记录。':'Choice recorded. This branch is complete; review it in your workspace.','看看其他选择':'Compare other choices','以下是预置教学对比，没有真实胜率或推理分数。':'These are preset comparisons, without real win rates or model scores.','示例推荐':'Example suggestion','也可以合法出牌，但会消耗不同点数的对子。实际优劣需要策略工具评估。':'Also legal, but uses a different pair. A strategy engine is needed to evaluate the trade-off.','保留手牌，将行动交给下家。后续收益取决于隐藏手牌和双方策略。':'Keep your cards and pass. The outcome depends on hidden cards and both sides’ strategies.','待确认局面':'Unconfirmed position','暂停建议 · 等待纠正':'Advice paused · Awaiting correction','需要你确认':'Confirmation needed','当前牌面存在冲突。确认牌面后，才能给出可靠建议。':'The observed cards conflict. Confirm the position before using advice.','等待局面确认':'Awaiting position confirmation','确认桌面上的牌':'Confirm the cards on the table','确认结果':'Confirmed position','空桌面，由我领出':'Empty table; I lead','仍然看不清':'Still unclear','保持暂停':'Keep paused','确认局面':'Confirm position','局面已确认，建议恢复。':'Position confirmed. Advice resumed.','建议保持暂停。可再次点击“识别有误？”确认。':'Advice remains paused. Open “Incorrect position?” to confirm later.','这一手的陪伴过程':'The companion loop for this move','这是流程演示，各步骤未调用真实模型。':'This demonstrates the workflow; no real models are called.','01 · 观察':'01 · Observe','读取预置手牌和公开出牌。':'Read the preset hand and public cards.','02 · 校验':'02 · Validate','03 · 建议':'03 · Suggest','展示预置候选；MoE 接入后负责工具调度与解释。':'Show preset options. A future MoE model will coordinate tools and explain choices.','04 · 反馈':'04 · Feedback','分别记录推荐动作和你的实际选择。':'Record suggested and actual decisions separately.','片段已结束，请重新演示后纠正。':'Scenario ended. Restart it before correcting the position.','当前需要比桌面更大的对子，或选择不出。':'Play a higher pair than the table, or pass.','你是领出方，需要出牌。':'You lead and must play a card.','这个教学片段支持单张或对子，请重新选择。':'This scenario supports singles or pairs. Select again.','请先确认当前局面。':'Please confirm the current position first.','已选择':'Selected','剩余':'Remaining','张':'cards',
'根据当前局面，我下一手可以怎么出？请区分已知信息与推测。':'What could I play next? Distinguish known information from assumptions.','根据我的出牌记录，你观察到了什么？不要从少量样本推断稳定偏好。':'What do my decisions show? Do not infer stable preferences from a small sample.','结合我的手动出牌记录，分析哪些选择值得复盘。信息不足时请直说。':'Review my manual decisions and suggest choices worth revisiting. Say when evidence is insufficient.',
'先输入游戏名称。':'Enter a game name first.','先输入你的问题。':'Enter your question first.','上一条问题仍在处理中。':'The previous question is still being processed.','尚未连接推理后端，请在本机启动原型。':'No inference backend connected. Start the local prototype.','存储空间不足，当前记录仅在本次页面保留。':'Storage is full. Records will last only for this page session.','无法持久保存，笔记仅在当前页面有效。':'Unable to save permanently. Notes last only for this session.'
});
const patterns=[
 [/^第 (\d+) \/ (\d+) 回合 · (.*)$/,(_,a,b,c)=>`Turn ${a} / ${b} · ${translate(c)}`],
 [/^第 (\d+) 个白方回合$/,(_,n)=>`White turn ${n}`],[/^第 (\d+) 回合$/,(_,n)=>`Turn ${n}`],
 [/^第 (\d+) \/ (\d+) 个决策$/,(_,a,b)=>`Decision ${a} / ${b}`],
 [/^敌人下一次攻击：(\d+) 点伤害$/,(_,n)=>`Next enemy attack: ${n} damage`],
 [/^已记录 (\d+) 次手动选择，其中 (\d+) 次与教学建议不同。$/,(_,n,m)=>`${n} manual decisions recorded; ${m} differ from the teaching suggestion.`],
 [/^最近 (\d+) 条 · 刷新后保留$/,(_,n)=>`Latest ${n} records · Saved across reloads`],
 [/^(\d+) 次手动选择$/,(_,n)=>`${n} manual decisions`],[/^(\d+) 次选择$/,(_,n)=>`${n} decisions`],
 [/^剩余 (\d+) 张$/,(_,n)=>`${n} cards left`],[/^决策 (\d+)$/,(_,n)=>`Decision ${n}`],[/^行动回合 (\d+)$/,(_,n)=>`Turn ${n}`],
 [/^对 ([A-Z0-9]+)$/,(_,n)=>`Pair of ${n}`],[/^出对 ([A-Z0-9]+)$/,(_,n)=>`Play pair of ${n}`],
 [/^打出 (.+)$/,(_,n)=>`Play ${translate(n)}`],[/^弃 (.+)$/,(_,n)=>`Discard ${translate(n)}`],
 [/^(\d+) 张$/,(_,n)=>`${n} cards`],[/^已保存 (.+) 的明确偏好。$/,(_,g)=>`Preferences saved for ${translate(g)}.`]
];
const ordered=Object.keys(dictionary).sort((a,b)=>b.length-a.length);let language='zh';try{language=localStorage.getItem('paiwise.language')==='en'?'en':'zh'}catch{}
const originals=new WeakMap(),attrs=new WeakMap();
function translate(text){const trim=text.trim();if(dictionary[trim])return text.replace(trim,dictionary[trim]);for(const [r,f]of patterns)if(r.test(trim))return text.replace(trim,trim.replace(r,f));let out=text;for(const key of ordered)if(key.length>1)out=out.split(key).join(dictionary[key]);return out.replace(/出对 ([A-Z0-9]+)/g,'Play pair of $1').replace(/对 ([A-Z0-9]+)/g,'pair of $1').replace(/You draw 东/g,'You draw East').replace(/Play 东/g,'Discard East').replace(/Play 白/g,'Discard White Dragon').replace(/进入纠错后，旧建议已暂停。此教学场景的确认结果为(.+)。/g,'Previous advice is paused. The expected position is $1.').replace(/确认当前Position v(\d+)，检查出牌类型。/g,'Confirm position v$1 and validate the card type.').replace(/确认当前局面 v(\d+)，检查出牌类型。/g,'Confirm position v$1 and validate the card type.').replace(/第 (\d+) 回合/g,'Turn $1').replace(/(\d+) 张/g,'$1 cards').replace(/(\d+) 次/g,'$1 times').replace(/(\d+) 点/g,'$1 points').replace(/ 次$/,' times').replace(/^对 ([A-Z0-9]+)/,'Pair of $1').replace(/已确认局面/g,'Confirmed position').replace(/片段演示/g,'Scenario demo').replace(/已选择/g,'Selected').replace(/：/g,': ')}
const skip=el=>el.closest('script,style,textarea,.desk-bubble p,[data-user-content],#language-toggle,.five-layout,.five-setup');
function apply(){observer.disconnect();document.documentElement.lang=language==='en'?'en':'zh-CN';document.querySelectorAll('option:not([value])').forEach(el=>el.setAttribute('value',el.textContent));const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(!n.parentElement||skip(n.parentElement))continue;let cache=originals.get(n);if(!cache||n.nodeValue!==cache.last)cache={original:n.nodeValue,last:n.nodeValue};const output=language==='en'?translate(cache.original):cache.original;if(n.nodeValue!==output)n.nodeValue=output;cache.last=output;originals.set(n,cache)}document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>{if(el.closest('.desk-bubble p,[data-user-content],#language-toggle'))return;let cache=attrs.get(el)||{};for(const key of ['placeholder','aria-label','title']){if(!el.hasAttribute(key))continue;const raw=el.getAttribute(key);if(!cache[key]||cache[key].last!==raw)cache[key]={original:raw,last:raw};const next=language==='en'?translate(cache[key].original):cache[key].original;el.setAttribute(key,next);cache[key].last=next}attrs.set(el,cache)});button.textContent=language==='en'?'中文':'English';button.setAttribute('aria-label',language==='en'?'Switch to Chinese':'切换为英文');button.setAttribute('aria-pressed',String(language==='en'));document.title=language==='en'?'Paiwise · Game companion':'牌伴 · 游戏助手';observer.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label','title']})}
const button=document.createElement('button');button.id='language-toggle';button.className='language-button';document.querySelector('.top-actions').prepend(button);const observer=new MutationObserver(apply);window.PaiwiseI18n={get language(){return language},translate};button.addEventListener('click',()=>{language=language==='en'?'zh':'en';try{localStorage.setItem('paiwise.language',language)}catch{}const draft=document.querySelector('#desk-memory')?.value;window.dispatchEvent(new Event('languagechange'));if(view==='backend'){renderDesk();if(draft!==undefined)document.querySelector('#desk-memory').value=draft}apply()});apply();
})();
