/* Five-player identity match. Original implementation; no external game assets. */
(function(root){
'use strict';
const CN={sha:'杀',shan:'闪',tao:'桃',wuzhong:'无中生有',guohe:'过河拆桥',shunshou:'顺手牵羊',juedou:'决斗',nanman:'南蛮入侵',wanjian:'万箭齐发',taoyuan:'桃园结义',wugu:'五谷丰登',jiedao:'借刀杀人',lebu:'乐不思蜀',shandian:'闪电',wuxie:'无懈可击',crossbow:'诸葛连弩',double:'雌雄双股剑',qinggang:'青釭剑',qinglong:'青龙偃月刀',spear:'丈八蛇矛',axe:'贯石斧',halberd:'方天画戟',bow:'麒麟弓',bagua:'八卦阵',offhorse:'进攻马',defhorse:'防御马'};
const EN={sha:'Slash',shan:'Dodge',tao:'Peach',wuzhong:'Ex Nihilo',guohe:'Dismantlement',shunshou:'Snatch',juedou:'Duel',nanman:'Barbarian Invasion',wanjian:'Arrow Barrage',taoyuan:'Peach Garden',wugu:'Harvest',jiedao:'Borrowed Sword',lebu:'Indulgence',shandian:'Lightning',wuxie:'Negate',crossbow:'Crossbow',double:'Double Swords',qinggang:'Qinggang Sword',qinglong:'Green Dragon Blade',spear:'Serpent Spear',axe:'Stone Axe',halberd:'Sky Piercer',bow:'Kylin Bow',bagua:'Eight Trigrams',offhorse:'Offensive Mount',defhorse:'Defensive Mount'};
const HEROES=[{id:'sunquan',cn:'孙权',en:'Sun Quan',kingdom:'wu',hp:4,skill:'制衡 / 救援'},{id:'liubei',cn:'刘备',en:'Liu Bei',kingdom:'shu',hp:4,skill:'仁德 / 激将'},{id:'guanyu',cn:'关羽',en:'Guan Yu',kingdom:'shu',hp:4,skill:'武圣'},{id:'zhangfei',cn:'张飞',en:'Zhang Fei',kingdom:'shu',hp:4,skill:'咆哮'},{id:'lvmeng',cn:'吕蒙',en:'Lü Meng',kingdom:'wu',hp:4,skill:'克己'}];
const ROLES={lord:['主公','Monarch'],loyalist:['忠臣','Loyalist'],rebel:['反贼','Rebel'],renegade:['内奸','Renegade']};
const RANGE={crossbow:1,double:2,qinggang:2,qinglong:3,spear:3,axe:3,halberd:4,bow:5};
const COUNTS={sha:30,shan:15,tao:8,wuzhong:4,guohe:6,shunshou:5,juedou:3,nanman:3,wanjian:1,taoyuan:1,wugu:2,jiedao:2,lebu:3,shandian:1,wuxie:3,crossbow:2,double:1,qinggang:1,qinglong:1,spear:1,axe:1,halberd:1,bow:1,bagua:2,offhorse:3,defhorse:3};
const hero=p=>HEROES.find(h=>h.id===p.hero);
const pname=(p,en=false)=>`${p.id+1}${en?' · ':'号 · '}${hero(p)[en?'en':'cn']}`;
const red=c=>c.suit==='heart'||c.suit==='diamond';
function rng(s){s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296}
function shuffle(s,a){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng(s)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function event(s,cn,en){s.log.push({cn,en});if(s.log.length>120)s.log.shift()}
function slot(c){return RANGE[c.type]?'weapon':c.type==='bagua'?'armor':['offhorse','defhorse'].includes(c.type)?c.type:null}
function alive(s){return s.players.filter(p=>p.alive)}
function order(s,start=0){return Array.from({length:5},(_,i)=>(start+i)%5).filter(i=>s.players[i].alive)}
function distance(s,a,b){if(a===b)return 0;const seats=alive(s).map(p=>p.id),n=Math.abs(seats.indexOf(a)-seats.indexOf(b));return Math.max(1,Math.min(n,seats.length-n)-(s.players[a].equip.offhorse?1:0)+(s.players[b].equip.defhorse?1:0))}
function range(p){return RANGE[p.equip.weapon?.type]||1}
function draw(s,id,n){const p=s.players[id];for(let i=0;i<n;i++){if(!s.deck.length){s.deck=shuffle(s,s.discard.splice(0));event(s,'弃牌堆洗回牌堆','The discard pile is reshuffled')}if(!s.deck.length)break;p.hand.push(s.deck.pop())}}
function allCards(p){return [...p.hand,...Object.values(p.equip),...p.delayed]}
function take(s,id,cid){const p=s.players[id];let i=p.hand.findIndex(c=>c.id===cid);if(i>=0)return p.hand.splice(i,1)[0];for(const k of Object.keys(p.equip))if(p.equip[k].id===cid){const c=p.equip[k];delete p.equip[k];return c}i=p.delayed.findIndex(c=>c.id===cid);if(i>=0)return p.delayed.splice(i,1)[0];throw Error('Card unavailable')}
function spend(s,id,ids){return ids.map(cid=>{const c=take(s,id,cid);s.discard.push(c);return c})}
function slashCards(p){return [...p.hand,...Object.values(p.equip)].filter(c=>c.type==='sha'||p.hero==='guanyu'&&red(c))}
function judge(s){if(!s.deck.length)s.deck=shuffle(s,s.discard.splice(0));const c=s.deck.pop();if(c)s.discard.push(c);return c}
function winner(s){const lord=s.players.find(p=>p.role==='lord'),live=alive(s);let win=null;if(!lord.alive)win=live.length===1&&live[0].role==='renegade'?'renegade':'rebel';else if(!live.some(p=>p.role==='rebel'||p.role==='renegade'))win='lord';if(win){s.done=true;s.winner=win;s.pending=[];s.phase='finished';event(s,win==='lord'?'主公与忠臣获胜':win==='rebel'?'反贼获胜':'内奸独胜',win==='lord'?'Monarch and Loyalist win':win==='rebel'?'Rebels win':'Renegade wins alone')}return !!win}
function kill(s,id,source){const p=s.players[id];p.alive=false;s.discard.push(...p.hand,...Object.values(p.equip),...p.delayed);p.hand=[];p.equip={};p.delayed=[];event(s,pname(p)+'阵亡，身份为'+ROLES[p.role][0],pname(p,true)+' is eliminated: '+ROLES[p.role][1]);if(winner(s))return;if(source!=null&&s.players[source].alive){if(p.role==='rebel')draw(s,source,3);else if(p.role==='loyalist'&&s.players[source].role==='lord'){const k=s.players[source];s.discard.push(...k.hand,...Object.values(k.equip));k.hand=[];k.equip={};event(s,'主公误杀忠臣，弃置所有手牌与装备','Monarch eliminated the Loyalist: all hand cards and equipment discarded')}}}
function damage(s,source,target,n=1,slash=false){const p=s.players[target];if(!p.alive)return;p.hp-=n;if(source!=null&&target===s.players.find(x=>x.role==='lord').id)s.players[source].suspicion+=2;event(s,pname(p)+'受到 '+n+' 点伤害',pname(p,true)+' takes '+n+' damage');if(p.hp<=0)s.pending.unshift({kind:'rescue',target,source,seats:order(s,s.active),cursor:0});if(slash&&source!=null&&s.players[source].equip.weapon?.type==='bow'&&(p.equip.offhorse||p.equip.defhorse))s.pending.splice(p.hp<=0?1:0,0,{kind:'bow',actor:source,target})}
function heal(s,target,n){const p=s.players[target];p.hp=Math.min(p.maxHp,p.hp+n)}
function queueEffect(s,e,negatable=true){s.pending.push(negatable?{kind:'nullify',effect:e,cancelled:false,seats:order(s,s.active),cursor:0}:e)}
function beginTurn(s,id){s.active=id;s.turn++;s.phase='play';const p=s.players[id];p.slashes=0;p.usedSlash=false;p.balance=false;p.given=0;p.rouseFailed=false;p.skip=false;event(s,pname(p)+'的回合',pname(p,true)+"'s turn");const delays=p.delayed.splice(0).reverse();for(const card of delays)queueEffect(s,{kind:'judgment',target:id,source:null,card});s.pending.push({kind:'drawphase',target:id})}
function nextTurn(s){if(s.done)return;const next=order(s,(s.active+1)%5)[0];beginTurn(s,next)}
function settle(s){let guard=0;while(!s.done&&guard++<300){const q=s.pending[0];if(!q){if(!s.players[s.active].alive){nextTurn(s);continue}if(s.phase==='discard'&&s.players[s.active].hand.length<=Math.max(0,s.players[s.active].hp)){nextTurn(s);continue}return}
 if(q.target!=null&&!s.players[q.target].alive){s.pending.shift();continue}
 if(q.kind==='nullify'){while(q.cursor<q.seats.length&&!s.players[q.seats[q.cursor]].hand.some(c=>c.type==='wuxie'))q.cursor++;if(q.cursor<q.seats.length)return;s.pending.shift();if(!q.cancelled)s.pending.unshift(q.effect);else{if(q.effect.kind==='judgment')s.discard.push(q.effect.card);event(s,'锦囊效果被无懈可击抵消','The tactic effect is negated')}continue}
 if(q.kind==='rescue'){if(s.players[q.target].hp>0){s.pending.shift();continue}while(q.cursor<q.seats.length&&!s.players[q.seats[q.cursor]].hand.some(c=>c.type==='tao'))q.cursor++;if(q.cursor<q.seats.length)return;s.pending.shift();kill(s,q.target,q.source);continue}
 if(['respond','duel','borrow','bow','dragon','axe','double','harvest','choose','assist'].includes(q.kind))return;
 s.pending.shift();const p=s.players[q.target];
 if(q.kind==='drawphase'){draw(s,q.target,2);if(p.skip){s.phase='discard';event(s,'乐不思蜀生效，跳过出牌阶段','Indulgence: play phase skipped')}continue}
 if(q.kind==='judgment'){const c=judge(s);event(s,'判定：'+(c?c.suit+' '+c.rank:'无牌'),'Judgment: '+(c?c.suit+' '+c.rank:'no card'));if(q.card.type==='lebu'){if(c?.suit!=='heart')p.skip=true;s.discard.push(q.card)}else if(c?.suit==='spade'&&c.rank>=2&&c.rank<=9){s.discard.push(q.card);damage(s,null,q.target,3)}else{const next=order(s,(q.target+1)%5).find(i=>!s.players[i].delayed.some(c=>c.type==='shandian'));if(next!=null)s.players[next].delayed.push(q.card);else s.discard.push(q.card)}continue}
 if(q.kind==='slash'){const weapon=s.players[q.source].equip.weapon?.type;const respond={kind:'respond',need:'shan',source:q.source,target:q.target,slash:true,ignoreArmor:weapon==='qinggang',card:q.card};s.pending.unshift(respond);continue}
 if(q.kind==='effect'){
  if(q.type==='wuzhong')draw(s,q.target,2);
  if(q.type==='taoyuan')heal(s,q.target,1);
  if(q.type==='guohe'||q.type==='shunshou'){if(allCards(p).length)s.pending.unshift({kind:'choose',actor:q.source,source:q.source,target:q.target,type:q.type})}
  if(q.type==='juedou')s.pending.unshift({kind:'duel',source:q.source,target:q.target,other:q.source});
  if(q.type==='nanman'||q.type==='wanjian')s.pending.unshift({kind:'respond',source:q.source,target:q.target,need:q.type==='nanman'?'sha':'shan'});
  if(q.type==='jiedao')s.pending.unshift({kind:'borrow',source:q.source,target:q.target,victim:q.victim});
  if(q.type==='wugu'&&s.harvest.length)s.pending.unshift({kind:'harvest',actor:q.target,target:q.target});
 }
 if(q.kind==='harvest-cleanup'){s.discard.push(...s.harvest);s.harvest=[]}
 }if(guard>=300)throw Error('Resolution limit');}
function create(options={}){const s={rng:(options.seed??Date.now())>>>0,deck:[],discard:[],players:[],pending:[],harvest:[],active:0,turn:0,seq:0,phase:'play',done:false,winner:null,log:[]};let ids=0;for(const [type,count]of Object.entries(COUNTS))for(let i=0;i<count;i++)s.deck.push({id:++ids,type,suit:['spade','heart','club','diamond'][(ids-1)%4],rank:(ids-1)%13+1});shuffle(s,s.deck);let roles=shuffle(s,['lord','loyalist','rebel','rebel','renegade']);if(options.role&&ROLES[options.role]){const i=roles.indexOf(options.role);[roles[0],roles[i]]=[roles[i],roles[0]]}let heroes=shuffle(s,HEROES.map(h=>h.id));if(options.hero&&HEROES.some(h=>h.id===options.hero)){const i=heroes.indexOf(options.hero);[heroes[0],heroes[i]]=[heroes[i],heroes[0]]}for(let i=0;i<5;i++){const maxHp=4+(roles[i]==='lord'?1:0);s.players.push({id:i,hero:heroes[i],role:roles[i],hp:maxHp,maxHp,alive:true,hand:[],equip:{},delayed:[],suspicion:0,slashes:0,balance:false,given:0,usedSlash:false})}for(let i=0;i<5;i++)draw(s,i,4);beginTurn(s,s.players.findIndex(p=>p.role==='lord'));settle(s);return s}
function actor(s){if(s.done)return null;const q=s.pending[0];return q?['nullify','rescue'].includes(q.kind)?q.seats[q.cursor]:q.actor??q.target:s.active}
function action(id,actor,kind,cn,en,extra={}){return {id,actor,kind,cn,en,...extra}}
function actions(s){if(s.done)return[];const who=actor(s),p=s.players[who],q=s.pending[0],a=[];const add=(id,kind,cn,en,extra)=>a.push(action(id,who,kind,cn,en,extra));
 if(q){
  if(q.kind==='assist'){for(const c of slashCards(p))add('response:'+c.id,'response','激将：为主公打出杀','Rouse: supply a Slash',{cards:[c.id]});add('pass','pass','拒绝激将','Decline Rouse');return a}
  if(q.kind==='nullify'||q.kind==='rescue'){const type=q.kind==='nullify'?'wuxie':'tao';for(const c of p.hand.filter(c=>c.type===type))add('response:'+c.id,'response',CN[type],EN[type],{cards:[c.id]});add('pass','pass','放弃响应','Pass');return a}
  if(q.kind==='harvest'){for(const c of s.harvest)add('pick:'+c.id,'pick',CN[c.type],EN[c.type],{cards:[c.id]});return a}
  if(q.kind==='choose'){if(s.players[q.target].hand.length)add('take:hand','take','随机选择一张手牌','Choose a random hidden hand card');for(const c of [...Object.values(s.players[q.target].equip),...s.players[q.target].delayed])add('take:'+c.id,'take',CN[c.type],EN[c.type]);return a}
  if(q.kind==='bow'){for(const k of ['offhorse','defhorse'])if(s.players[q.target].equip[k])add('horse:'+k,'horse',CN[k],EN[k]);add('pass','pass','放弃','Pass');return a}
  if(q.kind==='double'){for(const c of p.hand)add('discard:'+c.id,'discard','弃置 '+CN[c.type],'Discard '+EN[c.type],{cards:[c.id]});add('pass','pass','令对手摸一张','Let attacker draw');return a}
  if(q.kind==='axe'){const cards=[...p.hand,...Object.entries(p.equip).filter(([k])=>k!=='weapon').map(([,c])=>c)];for(let i=0;i<cards.length;i++)for(let j=i+1;j<cards.length;j++)add('axe:'+cards[i].id+','+cards[j].id,'axe','弃两张强制命中','Discard two to force damage',{cards:[cards[i].id,cards[j].id]});add('pass','pass','放弃追击','Do not pursue');return a}
  const need=q.kind==='respond'?q.need:'sha',cs=need==='sha'?slashCards(p):p.hand.filter(c=>c.type==='shan');for(const c of cs)add('response:'+c.id,'response','打出 '+(c.type===need?CN[need]:CN[c.type]+'（武圣）'),'Respond with '+EN[need],{cards:[c.id]});
  if(need==='sha'&&p.equip.weapon?.type==='spear')for(let i=0;i<p.hand.length;i++)for(let j=i+1;j<p.hand.length;j++)add('response:'+p.hand[i].id+','+p.hand[j].id,'response','丈八蛇矛：两张当杀','Serpent Spear: two cards as Slash',{cards:[p.hand[i].id,p.hand[j].id]});
  if(need==='shan'&&p.equip.armor?.type==='bagua'&&!q.ignoreArmor&&!q.armorTried)add('armor','armor','八卦阵判定','Eight Trigrams judgment');
  if(need==='sha'&&p.role==='lord'&&p.hero==='liubei'&&!q.jijiangTried&&alive(s).some(x=>x.id!==who&&hero(x).kingdom==='shu'))add('jijiang','jijiang','激将：请求蜀将出杀','Rouse: request a Shu ally Slash');
  add('pass','pass',q.kind==='borrow'?'交出武器':q.kind==='dragon'?'放弃追杀':'不响应，承受伤害',q.kind==='borrow'?'Surrender weapon':q.kind==='dragon'?'Stop pursuit':'Take damage');return a;
 }
 if(s.phase==='discard'){if(p.hero==='lvmeng'&&!p.usedSlash)add('keji','keji','克己：跳过弃牌','Self-restraint: skip discard');for(const c of p.hand)add('discard:'+c.id,'discard','弃置 '+CN[c.type],'Discard '+EN[c.type],{cards:[c.id]});return a}
 const targets=alive(s).filter(t=>t.id!==who),canSlash=p.slashes<1||p.hero==='zhangfei'||p.equip.weapon?.type==='crossbow';
 for(const c of p.hand){const equipment=slot(c);if(equipment){add('equip:'+c.id,'equip','装备 '+CN[c.type],'Equip '+EN[c.type],{cards:[c.id]});continue}
 if(c.type==='tao'&&p.hp<p.maxHp)add('heal:'+c.id,'heal','使用桃','Use Peach',{cards:[c.id]});
 if(c.type==='sha'||p.hero==='guanyu'&&red(c)){} // Slash actions are generated below, including equipment conversions.
 if(['wuzhong','nanman','wanjian','taoyuan','wugu'].includes(c.type))add('trick:'+c.id+':'+who,'trick','使用 '+CN[c.type],'Play '+EN[c.type],{cards:[c.id],targets:[who]});
 if(c.type==='shandian'&&!p.delayed.some(d=>d.type==='shandian'))add('delay:'+c.id+':'+who,'delay','放置闪电','Place Lightning',{cards:[c.id],targets:[who]});
 for(const t of targets){if(['guohe','shunshou'].includes(c.type)&&allCards(t).length&&(c.type!=='shunshou'||distance(s,who,t.id)<=1)||c.type==='juedou')add('trick:'+c.id+':'+t.id,'trick',CN[c.type]+' → '+pname(t),EN[c.type]+' → '+pname(t,true),{cards:[c.id],targets:[t.id]});if(c.type==='lebu'&&!t.delayed.some(d=>d.type==='lebu'))add('delay:'+c.id+':'+t.id,'delay','乐不思蜀 → '+pname(t),'Indulgence → '+pname(t,true),{cards:[c.id],targets:[t.id]});if(c.type==='jiedao'&&t.equip.weapon)for(const victim of alive(s).filter(v=>v.id!==t.id&&distance(s,t.id,v.id)<=range(t)))add('borrow:'+c.id+':'+t.id+':'+victim.id,'trick','借刀 '+pname(t)+' → '+pname(victim),'Borrow sword: '+pname(t,true)+' → '+pname(victim,true),{cards:[c.id],targets:[t.id,victim.id]})}
 }
 if(canSlash){const addSlash=(cards,skill)=>{const reduced={...p,equip:Object.fromEntries(Object.entries(p.equip).filter(([,c])=>!cards.includes(c.id)))};if(p.slashes>=1&&p.hero!=='zhangfei'&&reduced.equip.weapon?.type!=='crossbow')return;const effective={...s,players:s.players.map(x=>x.id===who?reduced:x)},validTargets=targets.filter(t=>distance(effective,who,t.id)<=range(reduced));for(const t of validTargets)add('slash:'+cards.join(',')+':'+t.id,'slash',(skill?'武圣 / ':'')+'杀 → '+pname(t),'Slash → '+pname(t,true),{cards,targets:[t.id]});if(p.equip.weapon?.type==='halberd'&&cards.length===p.hand.length&&cards.every(id=>p.hand.some(c=>c.id===id)))for(let i=0;i<validTargets.length;i++)for(let j=i+1;j<validTargets.length;j++){const ts=[validTargets[i].id,validTargets[j].id];add('slash:'+cards.join(',')+':'+ts.join(','),'slash','方天画戟 → '+ts.map(x=>x+1).join('、'),'Sky Piercer → '+ts.map(x=>x+1).join(', '),{cards,targets:ts});for(let k=j+1;k<validTargets.length;k++){const three=[...ts,validTargets[k].id];add('slash:'+cards.join(',')+':'+three.join(','),'slash','方天画戟 → '+three.map(x=>x+1).join('、'),'Sky Piercer → '+three.map(x=>x+1).join(', '),{cards,targets:three})}}};for(const c of slashCards(p))addSlash([c.id],c.type!=='sha');if(p.equip.weapon?.type==='spear')for(let i=0;i<p.hand.length;i++)for(let j=i+1;j<p.hand.length;j++)addSlash([p.hand[i].id,p.hand[j].id]);}
 if(p.hero==='sunquan'&&!p.balance){for(const c of [...p.hand,...Object.values(p.equip)])add('balance:'+c.id,'balance','制衡：重换 '+CN[c.type],'Balance: replace '+EN[c.type],{cards:[c.id]});if(p.hand.length>1)add('balance:'+p.hand.map(c=>c.id).join(','),'balance','制衡：重换全部手牌','Balance: replace all hand cards',{cards:p.hand.map(c=>c.id)})}
 if(p.hero==='liubei')for(const c of p.hand)for(const t of targets)add('give:'+c.id+':'+t.id,'give','仁德：'+CN[c.type]+' → '+pname(t),'Benevolence: '+EN[c.type]+' → '+pname(t,true),{cards:[c.id],targets:[t.id]});
 if(canSlash&&p.role==='lord'&&p.hero==='liubei'&&!p.rouseFailed&&alive(s).some(x=>x.id!==who&&hero(x).kingdom==='shu'))for(const t of targets.filter(t=>distance(s,who,t.id)<=range(p)))add('rouse:'+t.id,'rouse','激将：杀 → '+pname(t),'Rouse: Slash → '+pname(t,true),{targets:[t.id]});
 add('end','end','结束出牌','End play phase');return a;
}
function requestRouse(s,lord,victim,original){const donors=order(s,(lord+1)%5).filter(i=>i!==lord&&hero(s.players[i]).kingdom==='shu');if(donors.length)s.pending.unshift({kind:'assist',target:donors.shift(),remaining:donors,lord,victim,original:!!original});else s.players[lord].rouseFailed=true}
function respondSuccess(s,q,who){if(q.kind==='duel'){q.target=q.other;q.other=who;return}if(q.kind==='borrow'){s.pending.shift();s.pending.unshift({kind:'slash',source:who,target:q.victim});return}if(q.kind==='dragon'){s.pending.shift();s.pending.unshift({kind:'slash',source:who,target:q.victim});return}s.pending.shift();if(q.slash){const source=s.players[q.source],weapon=source.equip.weapon?.type;if(weapon==='qinglong'&&slashCards(source).length)s.pending.unshift({kind:'dragon',target:q.source,source:q.source,victim:who});if(weapon==='axe'&&source.hand.length+Object.keys(source.equip).length-1>=2)s.pending.unshift({kind:'axe',actor:q.source,target:who,source:q.source})}}
function step(state,id){let a=actions(state).find(a=>a.id===id);if(!a&&id.startsWith('balance:')){const p=state.players[actor(state)],ids=id.slice(8).split(',').map(Number);if(!state.pending.length&&state.phase==='play'&&p.hero==='sunquan'&&!p.balance&&ids.length&&new Set(ids).size===ids.length&&ids.every(cid=>[...p.hand,...Object.values(p.equip)].some(c=>c.id===cid)))a=action(id,p.id,'balance','制衡','Balance',{cards:ids})}if(!a)throw Error('Illegal or stale action');const s=JSON.parse(JSON.stringify(state)),who=a.actor,p=s.players[who],q=s.pending[0];s.seq++;s.last={actor:who,cn:a.cn,en:a.en,kind:a.kind};event(s,pname(p)+'：'+a.cn,pname(p,true)+': '+a.en);
 if(q){
  if(q.kind==='assist'){s.pending.shift();if(a.kind==='response'){spend(s,who,a.cards);if(s.active===who)p.usedSlash=true;if(q.original)respondSuccess(s,s.pending[0],q.lord);else{const lord=s.players[q.lord];lord.slashes++;lord.usedSlash=true;s.pending.unshift({kind:'slash',source:q.lord,target:q.victim})}}else if(q.remaining.length){q.target=q.remaining.shift();s.pending.unshift(q)}else if(!q.original)s.players[q.lord].rouseFailed=true}
  else if(q.kind==='nullify'){if(a.kind==='response'){spend(s,who,a.cards);q.cancelled=!q.cancelled;q.seats=order(s,(who+1)%5);q.cursor=0}else q.cursor++}
  else if(q.kind==='rescue'){if(a.kind==='response'){spend(s,who,a.cards);const target=s.players[q.target],bonus=target.role==='lord'&&target.hero==='sunquan'&&who!==target.id&&hero(p).kingdom==='wu'?2:1;heal(s,q.target,bonus)}else q.cursor++}
  else if(q.kind==='harvest'){const i=s.harvest.findIndex(c=>c.id===a.cards[0]);p.hand.push(s.harvest.splice(i,1)[0]);s.pending.shift()}
  else if(q.kind==='choose'){const t=s.players[q.target];const chosen=id==='take:hand'?t.hand[Math.floor(rng(s)*t.hand.length)].id:Number(id.split(':')[1]);const c=take(s,q.target,chosen);if(q.type==='shunshou')p.hand.push(c);else s.discard.push(c);s.pending.shift()}
  else if(q.kind==='bow'){if(a.kind==='horse')s.discard.push(take(s,q.target,s.players[q.target].equip[id.split(':')[1]].id));s.pending.shift()}
  else if(q.kind==='axe'){s.pending.shift();if(a.kind==='axe'){spend(s,who,a.cards);damage(s,who,q.target,1,true)}}
  else if(q.kind==='double'){if(a.kind==='discard')spend(s,who,a.cards);else draw(s,q.source,1);s.pending.shift()}
  else if(a.kind==='armor'){q.armorTried=true;const c=judge(s);event(s,'八卦阵判定：'+(c?c.suit+' '+c.rank:'空'),'Eight Trigrams: '+(c?c.suit+' '+c.rank:'empty'));if(c&&red(c))respondSuccess(s,q,who)}
  else if(a.kind==='jijiang'){q.jijiangTried=true;requestRouse(s,who,null,q)}
  else if(a.kind==='response'){spend(s,who,a.cards);if((q.need==='sha'||['duel','borrow','dragon'].includes(q.kind))&&s.active===who)p.usedSlash=true;respondSuccess(s,q,who)}
  else{ s.pending.shift();if(q.kind==='borrow'){const w=p.equip.weapon;if(w){take(s,who,w.id);s.players[q.source].hand.push(w)}}else if(q.kind!=='dragon')damage(s,q.kind==='duel'?q.other:q.source,who,1,q.slash)}
 }else if(a.kind==='rouse'){requestRouse(s,who,a.targets[0],null)}else if(a.kind==='end'){s.phase='discard'}else if(a.kind==='discard'){spend(s,who,a.cards)}else if(a.kind==='keji'){nextTurn(s)}else if(a.kind==='balance'){const n=a.cards.length;spend(s,who,a.cards);draw(s,who,n);p.balance=true}else if(a.kind==='give'){const c=take(s,who,a.cards[0]);s.players[a.targets[0]].hand.push(c);p.given++;if(p.given===2)heal(s,who,1)}else if(a.kind==='equip'){const c=take(s,who,a.cards[0]),k=slot(c);if(p.equip[k])s.discard.push(p.equip[k]);p.equip[k]=c}else if(a.kind==='heal'){spend(s,who,a.cards);heal(s,who,1)}else if(a.kind==='delay'){const c=take(s,who,a.cards[0]);s.players[a.targets[0]].delayed.push(c)}else if(a.kind==='slash'){const used=spend(s,who,a.cards);p.slashes++;p.usedSlash=true;for(const target of a.targets)queueEffect(s,{kind:'slash',source:who,target,card:used[0]},false)}else if(a.kind==='trick'){const c=spend(s,who,a.cards)[0];if(c.type==='wugu'){const n=alive(s).length;for(let i=0;i<n;i++){if(!s.deck.length)s.deck=shuffle(s,s.discard.splice(0));if(s.deck.length)s.harvest.push(s.deck.pop())}}const targets=['nanman','wanjian'].includes(c.type)?order(s,(who+1)%5).filter(t=>t!==who):['taoyuan','wugu'].includes(c.type)?order(s,who):a.targets.slice(0,1);for(const target of targets)queueEffect(s,{kind:'effect',type:c.type,source:who,target,victim:a.targets[1]});if(c.type==='wugu')s.pending.push({kind:'harvest-cleanup'})}
 settle(s);return s;
}
function attitude(s,who,target){const p=s.players[who],t=s.players[target],lord=s.players.find(x=>x.role==='lord');if(who===target)return 3;if(p.role==='rebel')return target===lord.id?-5:t.suspicion>=2?2:-1;if(p.role==='loyalist'||p.role==='lord')return target===lord.id?5:-Math.max(0.3,t.suspicion);const opponents=alive(s).filter(x=>x.id!==who&&x.id!==lord.id);return target===lord.id?(opponents.length?2:-5):-1}
function recommend(s){const list=actions(s);if(!list.length)return null;const who=actor(s),p=s.players[who],q=s.pending[0];const val=c=>({tao:9,shan:6,sha:4,wuxie:7,wuzhong:8}[c.type]||3);const score=a=>{if(q){if(q.kind==='assist')return a.kind==='response'&&attitude(s,who,q.lord)>0?70:a.kind==='pass'?0:-10;if(q.kind==='rescue')return a.kind==='response'&&attitude(s,who,q.target)>0?100:a.kind==='pass'?0:-20;if(q.kind==='nullify'){const e=q.effect,harm=!['taoyuan','wuzhong','wugu'].includes(e.type),protect=attitude(s,who,e.target)>0;return a.kind==='response'&&((harm===protect)!==q.cancelled)?40:a.kind==='pass'?0:-10}if(q.kind==='choose')return a.id==='take:hand'?3:5;if(q.kind==='harvest')return val(s.harvest.find(c=>c.id===a.cards[0]));if(a.kind==='armor')return 90;if(a.kind==='response')return 70;if(a.kind==='jijiang')return 60;if(a.kind==='axe')return attitude(s,who,q.target)<0?20:-20;return 0}
 if(a.kind==='heal')return 100;if(a.kind==='equip')return 70;if(a.kind==='keji')return 100;if(a.kind==='discard')return -val(p.hand.find(c=>c.id===a.cards[0]));if(a.kind==='rouse')return 10-10*attitude(s,who,a.targets[0]);if(a.kind==='slash')return 20-10*Math.min(...a.targets.map(t=>attitude(s,who,t)));if(a.kind==='trick'){const c=p.hand.find(c=>c.id===a.cards[0]);if(c.type==='wuzhong')return 90;if(['taoyuan','wugu'].includes(c.type))return p.hp<p.maxHp?20:1;if(['nanman','wanjian'].includes(c.type))return p.role==='rebel'?25:5;return 15-10*attitude(s,who,a.targets[0])}if(a.kind==='delay')return p.hand.find(c=>c.id===a.cards[0]).type==='shandian'?-10:5-10*attitude(s,who,a.targets[0]);if(a.kind==='balance')return a.cards.length===1&&p.hand.find(c=>c.id===a.cards[0])?.type==='shan'&&p.hand.filter(c=>c.type==='shan').length>1?10:-10;if(a.kind==='give')return p.given<2&&attitude(s,who,a.targets[0])>0&&p.hp<p.maxHp?40:-10;return 0};return list.reduce((best,a)=>score(a)>score(best)?a:best,list[0])}
function publicState(s){return {turn:s.turn,active:s.active,actor:actor(s),phase:s.phase,done:s.done,winner:s.winner,deckCount:s.deck.length,players:s.players.map(p=>({id:p.id,hero:p.hero,hp:p.hp,maxHp:p.maxHp,alive:p.alive,role:p.id===0||p.role==='lord'||!p.alive||s.done?p.role:'hidden',handCount:p.hand.length,hand:p.id===0?p.hand:undefined,equip:p.equip,delayed:p.delayed})),pending:s.pending[0]?{kind:s.pending[0].kind,target:s.pending[0].target,source:s.pending[0].source,need:s.pending[0].need,lord:s.pending[0].lord}:null}}
const api={CN,EN,HEROES,ROLES,RANGE,create,actions,actor,step,recommend,publicState,distance,range,cardSlot:slot,hero,pname};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Sanguosha=api;
})(typeof globalThis==='undefined'?this:globalThis);
