'use strict';
const simulations=Object.create(null);let gameTimer=null,gameAuto=false;
function simState(){const key=gameScope();return simulations[key]??=(SimEngine.create(currentGame))}
function simulationSnapshot(){const s=simState();return {mode:'简化教学模拟',game:gameTitle(),version,turn:s.turn,phase:s.phase,hand:s.hand,table:s.table,hp:s.hp,enemy:s.enemy,energy:s.energy,block:s.block,board:s.board,done:s.done,result:s.result}}
function stopGameAuto(){clearTimeout(gameTimer);gameTimer=null;gameAuto=false;const b=$('#sim-auto');if(b)b.textContent='播放模拟'}
const twoWorkspaceShow=showView;
showView=function(v){stopGameAuto();twoWorkspaceShow(v);if(view==='observer'){$('#breadcrumb').textContent='游戏模拟 · '+gameTitle();$('.demo-badge').textContent='简化教学 · 本机运行'}};
function gameCards(s){if(s.game==='chess'){
 const pieces={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
 return `<div class="mini-chess" aria-label="当前棋盘">${Array.from({length:64},(_,i)=>{const f='abcdefgh'[i%8],rank=8-Math.floor(i/8),square=f+rank,p=s.board[square];return `<div class="chess-square ${(i%8+Math.floor(i/8))%2?'dark':''}" aria-label="${square} ${p?pieces[p]:'空'}"><small>${square}</small><span>${p?pieces[p]:''}</span></div>`}).join('')}</div>`}
 return `<div class="sim-hand ${s.game==='mahjong'?'tiles':''}" aria-label="当前手牌">${s.hand.map((c,i)=>`<div class="sim-card"><small>${s.game==='sanguosha'?'基础牌':s.game==='spire'?(c==='重击'?'2':'1')+' 能量':s.game==='mahjong'?'麻将':i%2?'♥':'♠'}</small><strong>${escapeHTML(c)}</strong><span>${s.game==='spire'?(c==='防御'?'格挡 5':c==='重击'?'伤害 9':'伤害 6'):''}</span></div>`).join('')}</div>`;
}
function gameStats(s){if(s.game==='sanguosha')return [['你 · 练习武将',s.hp+' / 4 体力'],['对手 · 固定策略',s.enemy+' / 3 体力'],['阶段',s.phase==='defend'?'响应对手的杀':'你的出牌阶段']];if(s.game==='spire')return [['你的生命',s.hp+' / 30'],['训练敌人',s.enemy+' / 26'],['能量 / 格挡',s.energy+' / '+s.block]];if(s.game==='custom')return [['生命',s.hp+' / 6'],['资源',s.resource+' / 8'],['推进',s.progress+' 点']];if(s.game==='chess')return [['你','白方'],['对手','黑方 · 固定回应'],['阶段','第 '+s.turn+' 个白方回合']];if(s.game==='guandan')return [['你','南家 · '+s.hand.length+' 张'],['队友','北家 · 脚本控制'],['对手','东 / 西家 · 脚本控制']];return [['你','东家 · '+s.hand.length+' 张'],['其他三家','自动摸打'],['已弃牌',s.discards.length+' 张']]}
renderObserver=function(){const s=simState(),a=SimEngine.actions(s),rec=SimEngine.recommend(s);const message=s.done?s.result:s.game==='spire'?'敌人下一次攻击：'+SimEngine.intent(s)+' 点伤害':s.game==='sanguosha'?s.phase==='defend'?'对手使用杀，请选择如何响应':'轮到你出牌，选择一张基础牌或结束回合':s.game==='guandan'?s.table.length?'桌面：对 '+s.table[0]+' · 请选择更大的对子':'你获得领出权，可以出任意手中对子':s.game==='mahjong'?'请选择一张手牌打出':s.game==='chess'?'白方行棋 · 从下方选择开局走法':'选择本回合的策略';
 $('#observer').innerHTML=`<div class="page-heading"><div><div class="eyebrow">01 / GAME SIMULATOR</div><h1>${escapeHTML(gameTitle())} · 模拟对局</h1><p>每次操作更新局面，记录同步到用户后台。</p></div><div class="board-controls"><button class="button secondary" data-go="library">切换游戏</button><button class="button secondary" id="sim-reset">重新开始</button><button class="button primary" id="sim-auto" ${s.done?'disabled':''}>${gameAuto?'暂停模拟':'播放模拟'}</button></div></div><div class="sim-layout"><div><div class="sim-arena ${s.game}"><div class="sim-top"><strong>${escapeHTML(gameTitle())}</strong><span>第 ${s.turn} / ${s.maxTurns} 回合 · ${s.done?'已结束':'进行中'}</span></div><div class="sim-players">${gameStats(s).map(([k,v])=>`<div><small>${escapeHTML(k)}</small><strong>${escapeHTML(v)}</strong></div>`).join('')}</div><div class="sim-message" role="status">${escapeHTML(message)}</div>${s.game==='custom'?`<div class="sim-progress"><strong>${s.progress}</strong><span>累计推进点数</span><progress value="${s.turn}" max="4"></progress></div>`:gameCards(s)}${s.table.length&&s.game!=='chess'?`<div class="sim-table">${escapeHTML(s.table.join(' · '))}</div>`:''}</div><section class="surface sim-actions"><div class="section-title"><h2>${s.done?'本次练习结束':'选择你的动作'}</h2><span>${s.done?s.seq+' 次选择':'只列出当前可用动作'}</span></div>${s.done?`<p>${escapeHTML(s.result)}</p><div class="board-controls"><button class="button primary" id="sim-again">再来一局</button><button class="button secondary" data-go="backend">查看本游戏记录 ↗</button></div>`:`<div class="sim-options">${a.map(x=>`<button class="sim-option ${x.id===rec?.id?'suggested':''}" data-sim-action="${escapeHTML(x.id)}" data-sim-version="${version}"><strong>${escapeHTML(x.label)}</strong><small>${escapeHTML(x.hint)}</small></button>`).join('')}</div>`}</section><section class="surface"><div class="section-title"><h2>对局动态</h2><span>最近 6 次</span></div><div class="sim-events">${s.log.length?s.log.slice(-6).reverse().map(e=>`<p><span>第 ${e.turn} 回合</span>${escapeHTML(e.text)}</p>`).join(''):'<p>等待你的第一步操作。</p>'}</div></section></div><aside><section class="surface sim-guide"><span class="coach-symbol">✦</span><h2>教学提示</h2><p>${s.done?'本次练习完成，可以到后台回看不同选择。':rec?'示例选择：'+escapeHTML(rec.label):'等待下一回合'}</p><p class="desk-small">提示由固定规则生成，不是模型推理，也不代表最优策略。</p><button class="button primary" data-go="backend">用户后台 ↗</button></section><section class="surface"><h2>本练习的规则范围</h2><p class="desk-small">${escapeHTML(SimEngine.rules[s.game])}</p></section><section class="surface"><h2>偏好与记忆</h2><p class="desk-small">手动操作和自动播放分别记录；本游戏的记录不会混入其他游戏。</p></section></aside></div>`;
};
function performSim(id,source='user',expected=version){if(expected!==version)return;const old=simState(),rec=SimEngine.recommend(old),snapshot={hand:[...old.hand],table:[...old.table],turn:old.turn};if(source==='user')stopGameAuto();try{const next=SimEngine.step(old,id);simulations[gameScope()]=next;version++;const row=next.log.at(-1);decisionLog.push({scope:gameScope(),game:gameTitle(),source,step:next.seq,action:row.action,recommended:rec?.label||'无',adopted:rec?.id===id,reason:row.text,snapshot,session:sessionKey,time:Date.now()});decisionLog=decisionLog.slice(-200);persistDesk();if(next.done)stopGameAuto();renderObserver()}catch(e){stopGameAuto();toast(e.message)}}
function simTick(){if(!gameAuto||view!=='observer')return stopGameAuto();const rec=SimEngine.recommend(simState());if(!rec)return stopGameAuto();performSim(rec.id,'simulation');if(gameAuto)gameTimer=setTimeout(simTick,1800)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.simAction)return performSim(b.dataset.simAction,'user',Number(b.dataset.simVersion));if(b.id==='sim-reset'||b.id==='sim-again'){stopGameAuto();simulations[gameScope()]=SimEngine.create(currentGame);version++;sessionKey=Date.now().toString(36);renderObserver()}if(b.id==='sim-auto'){if(gameAuto){stopGameAuto();return}gameAuto=true;b.textContent='暂停模拟';gameTimer=setTimeout(simTick,1200)}});
// Restore the selected workspace after installing the game-specific renderer.
showView(view==='backend'?'backend':'library');
