const assert=require('node:assert/strict');const E=require('../sanguosha-engine');
function cards(s){return [...s.deck,...s.discard,...s.harvest,...s.players.flatMap(p=>[...p.hand,...Object.values(p.equip),...p.delayed]),...s.pending.flatMap(q=>q.kind==='judgment'?[q.card]:q.kind==='nullify'&&q.effect.kind==='judgment'?[q.effect.card]:[])];}
for(let seed=1;seed<=100;seed++){let s=E.create({seed}),count=0;assert.equal(cards(s).length,104);assert.deepEqual(s.players.map(p=>p.role).sort(),['lord','loyalist','rebel','rebel','renegade']);assert.equal(s.players.find(p=>p.role==='lord').maxHp,5);while(!s.done&&count++<2500){const offered=E.actions(s);assert.ok(offered.length);const before=JSON.stringify(s);assert.throws(()=>E.step(s,'not-legal'));const next=E.step(s,E.recommend(s).id);assert.equal(JSON.stringify(s),before,'pure transition');assert.equal(cards(next).length,104,`card conservation seed=${seed} action=${count}`);assert.equal(new Set(cards(next).map(c=>c.id)).size,104);s=next}assert.ok(s.done,'AI match terminates');assert.deepEqual(E.actions(s),[]);assert.throws(()=>E.step(s,'end'));}
function fixture(hero='sunquan',role='lord'){let s=E.create({seed:8,hero,role});s.pending=[];s.active=0;s.phase='play';s.players[0].slashes=0;return s}
function card(s,type,id=0){for(const p of s.players){const i=p.hand.findIndex(c=>c.type===type);if(i>=0){const c=p.hand.splice(i,1)[0];s.players[id].hand.push(c);return c}}const i=s.deck.findIndex(c=>c.type===type);assert.ok(i>=0);const c=s.deck.splice(i,1)[0];s.players[id].hand.push(c);return c}
let s=fixture();let p=E.publicState(s);assert.equal(p.players.filter(x=>x.role==='hidden').length,4);assert.ok(p.players.slice(1).every(x=>x.hand===undefined));assert.equal(p.deck,undefined);
let a=card(s,'sha');assert.ok(E.actions(s).some(x=>x.id===`slash:${a.id}:1`));assert.ok(!E.actions(s).some(x=>x.id===`slash:${a.id}:2`));s.players[1].alive=false;assert.equal(E.distance(s,0,2),1);
s=fixture();const balance=s.players[0].hand.slice(0,2).map(c=>c.id);let n=E.step(s,'balance:'+balance.join(','));assert.equal(n.players[0].hand.length,s.players[0].hand.length);assert.ok(n.players[0].balance);assert.ok(!E.actions(n).some(a=>a.kind==='balance'));
s=fixture('lvmeng');s.phase='discard';s.players[0].usedSlash=false;assert.ok(E.actions(s).some(a=>a.id==='keji'));s.players[0].usedSlash=true;assert.ok(!E.actions(s).some(a=>a.id==='keji'));
s=fixture('liubei');let rouse=E.actions(s).find(a=>a.kind==='rouse');assert.ok(rouse);n=E.step(s,rouse.id);assert.equal(n.pending[0].kind,'assist');assert.notEqual(E.actor(n),0);while(n.pending[0]?.kind==='assist')n=E.step(n,'pass');assert.ok(n.players[0].rouseFailed);assert.ok(!E.actions(n).some(a=>a.kind==='rouse'));
// Lethal damage creates a Peach response, then resolves faction victory.
s=fixture('sunquan','rebel');const lord=s.players.find(p=>p.role==='lord');lord.hp=1;const peach=card(s,'tao',lord.id);s.pending=[{kind:'respond',source:0,target:lord.id,need:'shan',slash:true}];n=E.step(s,'pass');assert.equal(n.done,false);assert.equal(n.pending[0].kind,'rescue');let guard=0;while(n.pending[0]?.kind==='rescue'&&E.actor(n)!==lord.id&&guard++<6)n=E.step(n,'pass');assert.equal(E.actor(n),lord.id);n=E.step(n,'response:'+peach.id);assert.equal(n.players[lord.id].hp,1);assert.equal(n.players[lord.id].alive,true);
s.pending=[{kind:'respond',source:0,target:lord.id,need:'shan',slash:true}];n=E.step(s,'pass');guard=0;while(!n.done&&n.pending[0]?.kind==='rescue'&&guard++<10)n=E.step(n,'pass');assert.equal(n.done,true);assert.equal(n.winner,'rebel');
console.log('PASS: 100 complete matches; 104-card conservation; immutable actions; identity redaction; distance; skills; rescue and victory');
